import R56Audit.Parameters
import R56Audit.Digits
import R56Audit.Measurability
import R56Audit.OneRectangle
import R56Audit.StageGeometry
import R56Audit.GoodTransitionsArchive
import R56Audit.AllBases

/-!
Auditor's supplement to the Lean archive of "Tight Bounds for Tusnády's Problem in the Plane"
(not part of the audited archive). Manuscript: `tusnady-plane-stoc27-vC-r65`.

The supplement formalizes the proof of the manuscript as it is written: the numbered
statements, the displays (1)–(18), the definitions of Sections 1–2 and of the appendix, and
the steps of the proofs are stated in the manuscript's own terms, and Theorem 1.1 is derived
from them. `audit-claude/Gates.lean` lists the statements in the order of the manuscript;
`audit-claude/AUDIT_CLAUDE.md` records how each one compares with the manuscript.

| Manuscript | Module | Statements |
| --- | --- | --- |
| `F_χ`, `‖F_χ‖∞` (Section 1) | `Notation`, `SupNorm` | `F`, `supNorm`, `exists_eq_supNorm` |
| Theorem 1.1 | `Parameters` | `theorem_1_1`, `theorem_1_1_unfolded`, `theorem_1_1_constant` |
| Corollary 1.2, lower bound | `Parameters` | `exists_points`, `corollary_1_2_lower` |
| the event of Section 2.1 | `GoodTransitions` | `SetupEvent`, `ae_setupEvent` |
| endpoint average, display (2) | `LocalGain`, `EndpointAverage`, `Potential` | `endAvg`, `endpointAvg_eq_F` |
| `osc`, `mid`, display (3) | `Osc`, `StepOsc` | `osc`, `mid`, `osc_add_le`, `abs_osc_add_sub_le` |
| Lemma 2.1, display (4) | `Osc` | `vertical_comparison` |
| Fact 2.2 | `SymmetricSumsGeneral` | `fact_2_2_general` |
| Lemma 2.3, displays (5)–(8) | `LocalGain` | `local_gain`, `display_5`, `display_6`, `finAvg_childMean`, `display_8` |
| the remark after Lemma 2.3 | `OneRectangle` | `one_rectangle` |
| stages, cells, comparison rectangles | `StageGeometry` | `cell`, `compRect`, `innerRegion_eq_diff` |
| the potential `Z_j`, displays (1), (9) | `Potential`, `Measurability` | `Zpot`, `Zpot_le_two_supNorm`, `measurable_Zpot` |
| the σ-fields `𝓕_j`, the next digits | `StageFiltration`, `Digits` | `stageSigma`, `digitSigma`, `condExp_digitSigma`, `condExp_nextDigits` |
| display (10) | `ConditionalGain`, `Digits` | `roadmap`, `roadmap_digits`, `fluctDigits` |
| Lemma 2.4, display (11) | `StageGain`, `ConditionalGain`, `Digits` | `lemma_2_4`, `lemma_2_4_digits` |
| Lemma 2.5, display (12) | `GoodTransitions`, `Crowding` | `lemma_2_5_i`, `lemma_2_5_ii`, `lemma_2_5_ii_all` |
| Fact A.1 | `BoundedDifferencesGeneral` | `fact_A_1`, `fact_A_1_integrable` |
| Lemma 2.6, display (13) | `Influence`, `SuccessiveConditioning`, `Fluctuations`, `Digits` | `lemma_2_6`, `lemma_2_6_digits`, `Zstep_update_le`, `integral_prod_le_of_condExp_le` |
| Proposition 2.7, display (14) | `Simultaneous` | `proposition_2_7`, `fluct_le_of_good`, `prob_exists_small_le` |
| Parameters, displays (15)–(18) | `Parameters` | `exists_base_of_15`, `display_16`, `display_17`, `display_18` |

**The route.** `theorem_1_1` ← `proposition_2_7` ← { display (10) `roadmap_digits`;
`lemma_2_4_digits` ← `lemma_2_4` ← `local_gain` ← `vertical_comparison` and
`fact_2_2_general`; `lemma_2_5_i`; `lemma_2_5_ii_all`; `lemma_2_6_digits` ← `lemma_2_6` ←
`Zstep_update_le`, `fact_A_1` and `integral_prod_le_of_condExp_le` }, for the potential of
display (1) with its extrema over the continuum of heights, and for every integer base
`b ≥ 3`. The archive's own proof (base `2^L`, even-base local gain, finite-probe potential)
is not used. `audit-claude/Gates.lean` checks this route mechanically.

**The σ-fields.** The manuscript's `𝓕_j` is generated by all heights and by the first `j`
base-`b` digits of every horizontal coordinate (`digitSigma`). Proposition 2.7 is proved from
the statements for these σ-fields (`roadmap_digits`, `lemma_2_4_digits`, `lemma_2_6_digits`).
Those are derived from the same statements for the σ-field generated by the heights and by
the index of the stage-`j` interval that contains each horizontal coordinate (`stageSigma`):
on the probability-one event of Section 2.1 the two families of generators determine each
other, so conditional expectations agree almost surely (`condExp_digitSigma`).

**Two forms of some statements.** Several steps are proved once in a general form and then
stated in the manuscript's form: Lemma 2.1 and the displays of Lemma 2.3 for arbitrary sets of
heights (`vertical_comparison_sets`, `avg_comparison_core`, `offset_core`, …) and then for the
blocks of an interval (`vertical_comparison`, `display_5`, `offset_eq`, …); the conditional
gain and the fluctuation bound for the potential as a function of heights and interval
indices (`Zstep_gain`, `condExp_exp_step`) and then for `Z_j` and `𝓕_j` (`lemma_2_4`,
`lemma_2_6_step2`). So some statements in the manuscript's form are not on the dependency
route of `theorem_1_1` themselves; they are proved from the general forms that are (for
instance `display_5`, `offset_eq`, `lemma_2_6_step2`, `condExp_nextDigits`).

**Statements that Theorem 1.1 does not use.** `audit-claude/Gates.lean` pins the statements
of the supplement that correspond to the manuscript, and prints which of them are not used by
`theorem_1_1` or `corollary_1_2_lower`. These are:

* `theorem_1_1_unfolded`, which is derived from `theorem_1_1`, and the remark `one_rectangle`;
* restatements in the manuscript's form, proved from definitions and general forms that are
  on the route: `display_5`, `offset_eq`, `withoutJumps_eq`, `lemma_2_6_step2`,
  `condExp_nextDigits`;
* statements of the manuscript that the proofs here do not need in that form: `ae_setupEvent`
  (the proofs use `ae_inUnit`, `ae_noGrid` and the distinct heights separately), `display_6`,
  "`Z_j` is `𝓕_j`-measurable", the equality `volume_boundaryStrips` (the proof needs the upper
  bound only), and the conditional forms `condExp_exp_le_cosh`, `condExp_exp_le_exp_sq` of
  "One difference";
* Lemma 2.3 for arbitrary sets of heights (`local_gain_core`, `local_gain_sets`,
  `expected_offset_core`), which serves the archive's probe route in `GridDrift` only;
* the identifications `childAvg_eq_F`, `nextDigits_ae_eq_freshInfo` and `fluctTerm_ae_eq`,
  which say what `childAvg`, the archive's `freshGridIndex` and the terms of `fluctStep` are,
  and two remarks on hypotheses (`inUnit_of_noGrid`, `exists_symm_perm_iff`);
* set-level geometry and counting that the proofs do not need: all of `StageGeometry`, the
  facts about the blocks in `Osc` (`iUnion_block`, `block_disjoint`, `iUnion_inner_blocks`,
  `inner_blocks_nonempty`), `exists_childIndex`, `mem_innerPoints_iff`, and the weak form
  `volume_innerRegions_le`;
* measurability of the events, of `Z_j` and of the next digits; attainment of the extrema;
  `fact_A_1_integrable`;
* the statements about the archive's routes.

**What is used of the archive** by the results above (`audit-claude/Closure.lean` lists it):
eight modules. The law `unifPts` of the points, its coordinate split, and two null events
(`Oscillation.CoordinateProduct`, `Riesz.PointSets`: `Oscillation.ae_pointSampleLaw_mem_Ioc`,
`Riesz.PointSets.diag_null`); finite averages (`Oscillation.finAvg`); the index
`Riesz.gridIndex` of the interval `(c/k, (c+1)/k]` that contains a number and the next digit
`Riesz.freshGridIndex`; and one statement of the manuscript that the supplement does not
prove itself: "The `(j+1)`-st digits \[…\] are independent and uniform conditional on `𝓕_j`"
is the archive's `Riesz.condExp_freshGrid_with_past` (the manuscript states it without
proof). Corollary 1.2 uses in addition the archive's definition `Δ₂` of the discrepancy
function and its elementary lemmas. Lemma 2.1, Fact 2.2, Lemma 2.5(i), Fact A.1 and the two
facts of `SuccessiveConditioning` use Mathlib only.

**Modules about the archive's routes**, not used above:

* `ArchiveInterface`: `F_χ`, `‖F_χ‖∞` and the archive's point-set interface (`badSet`,
  `GoodEvent`, `Δ₂`); only `lt_Δ₂_of_supNorm` is used above, for Corollary 1.2.
* `ArchiveRoute`: the archive's theorems restated with `F_χ` and `‖F_χ‖∞`
  (`theorem_1_1_archive`, …).
* `GoodTransitionsArchive`: the archive's good-transition event is the event `G_j` of the
  manuscript, almost surely.
* `GridDrift`, `AllBases`: the archive's finite-probe proof of Proposition 2.7 with the parity
  restriction removed (`proposition_2_7_probe`), a second proof of display (14).

**Not formalized:** the upper bound of Corollary 1.2 (Nikolov's theorem, cited); Section 3;
the heuristic remarks of the introduction and of Section 2 (density of points per rectangle,
"about `(1-2/b)n` points", the comparison with Khintchine's inequality, the remark on the
power `b⁻⁵`). `audit-claude/AUDIT_CLAUDE.md` lists them, together with the few places where
a proof here is organized differently from the manuscript's.
-/
