import R56Audit.StageFiltration
import R56Audit.GoodTransitions

/-!
# Lemma 2.4 of the manuscript (conditional gain) and the identity (10)

Auditor's supplement (not part of the audited archive).

**Lemma 2.4.** For every `0 ≤ j < h`, almost surely

`E[Z_{j+1} - Z_j | 𝓕_j] ≥ δ_j := (1 / (4bM)) Σ_R √(m_R)`,

where `R` ranges over the `M` comparison rectangles of the transition `j → j+1`.

Here `Z_j` is the potential `Zpot` of display (1), with its extrema over the continuum of
heights; `𝓕_j` is `stageSigma n b j`; the conditional expectation is Mathlib's `condExp` for
the law `unifPts n` of `n` independent uniform points of the unit square; and `δ_j` is
`delta b h j` with the regions of the manuscript (`GoodTransitions.lean`). The statements for
the σ-field `digitSigma n b j` generated by the heights and the first `j` digits, which is the
manuscript's `𝓕_j`, are `lemma_2_4_digits` and `roadmap_digits` in `Digits.lean`; they follow
from the statements of this file.

**Display (10).** `Z_h = Z_0 + Σ_{j<h} E[Z_{j+1} - Z_j | 𝓕_j] + T`, where
`T = Σ_{j<h} (Z_{j+1} - E[Z_{j+1} | 𝓕_j])` is the fluctuation term (`fluct`).

* `lemma_2_4`: Lemma 2.4. The proof is the manuscript's: Lemma 2.3 (`local_gain`) in every
  comparison rectangle (`Zstep_gain`, `Zmean_ge`), the next digits being independent and
  uniform conditional on `𝓕_j` (`condExp_Zproc_succ`).
* `roadmap`: display (10), almost surely.
* `Zpot_aestronglyMeasurable`, `condExp_Zpot_self`: "`Z_j` is `𝓕_j`-measurable".
* `delta_eq_deltaStep`: on the probability-one event that no point lies on a grid line, `δ_j`
  is determined by the heights and the stage-`j` indices.
-/

namespace R56Audit

open MeasureTheory Finset Riesz Riesz.PointSets Oscillation

noncomputable section

variable {n : ℕ}

/-! ### `δ_j` in terms of the heights and the indices -/

/-- If no point lies on a grid line, the points of the inner region of the comparison
rectangle `(c, v)` are those with stage-`j` index `c` whose height lies in the inner blocks. -/
lemma innerCount_eq_card_innerSet {b : ℕ} (hb : 0 < b) (h j c v : ℕ) (P : Fin n → ℝ × ℝ)
    (hgrid : NoGrid b P) :
    innerCount b h j P c v =
      (innerSet b h j (coarseInfo n (b ^ j) P).1 (coarseInfo n (b ^ j) P).2 c v).card := by
  classical
  have hbR : (0 : ℝ) < b := by exact_mod_cast hb
  have e1 : (v : ℝ) * vlen b h (j + 1) + vlen b h j =
      ((v : ℝ) * (b : ℝ) ^ (j + 1) + (b : ℝ) ^ j) / (b : ℝ) ^ h := by
    unfold vlen
    ring
  have e2 : (v : ℝ) * vlen b h (j + 1) + ((b : ℝ) - 1) * vlen b h j =
      (((v : ℝ) + 1) * (b : ℝ) ^ (j + 1) - (b : ℝ) ^ j) / (b : ℝ) ^ h := by
    unfold vlen
    rw [pow_succ]
    ring
  unfold innerCount innerSet innerPoints
  congr 1
  ext i
  simp only [Finset.mem_filter, Finset.mem_univ, true_and]
  change P i ∈ innerRegion b h j c v ↔
    sideIdx (gridIndex (b ^ j) (P i).1) c = Side.inside ∧
      (v : ℝ) * vlen b h (j + 1) + vlen b h j ≤ (P i).2 ∧
      (P i).2 < (v : ℝ) * vlen b h (j + 1) + ((b : ℝ) - 1) * vlen b h j
  rw [e1, e2, ← sideOf_grid hb j c (P i).1, sideOf_eq_inside_iff]
  have hx : (P i).1 ≠ (c : ℝ) / (b : ℝ) ^ j := by
    have := (hgrid i (c : ℤ) j).1
    push_cast at this
    exact this
  unfold innerRegion
  simp only [Set.mem_prod, Set.mem_Icc, Set.mem_Ico]
  constructor
  · rintro ⟨⟨h1, h2⟩, h3, h4⟩
    exact ⟨⟨lt_of_le_of_ne h1 (Ne.symm hx), h2⟩, h3, h4⟩
  · rintro ⟨⟨h1, h2⟩, h3, h4⟩
    exact ⟨⟨h1.le, h2⟩, h3, h4⟩

/-- If no point lies on a grid line, `δ_j` is the number read from the heights and the
stage-`j` indices. -/
theorem delta_eq_deltaStep {b : ℕ} (hb : 0 < b) (h j : ℕ) (P : Fin n → ℝ × ℝ)
    (hgrid : NoGrid b P) :
    delta b h j P =
      deltaStep b h j (coarseInfo n (b ^ j) P).1 (coarseInfo n (b ^ j) P).2 := by
  unfold delta deltaStep
  congr 1
  refine Finset.sum_congr rfl fun c _ => Finset.sum_congr rfl fun v _ => ?_
  rw [innerCount_eq_card_innerSet hb h j c v P hgrid]

/-! ### Conditional expectations of the potential -/

lemma integrable_Zpot {b h j : ℕ} (hb : 0 < b) (hj : j ≤ h) (χ : Fin n → ℤˣ) :
    Integrable (Zpot χ b h j) (pointSampleLaw n) :=
  (integrable_Zproc hb (sgn χ) (fun i => (abs_sgn χ i).le) h j).congr
    (Zpot_ae_eq_Zproc hb hj χ).symm

/-- `E[Z_j | 𝓕_j] = Z_j` almost surely: `Z_j` is `𝓕_j`-measurable. -/
lemma condExp_Zpot_self {b h j : ℕ} (hb : 0 < b) (hj : j ≤ h) (χ : Fin n → ℤˣ) :
    (pointSampleLaw n)[Zpot χ b h j | stageSigma n b j] =ᵐ[pointSampleLaw n] Zpot χ b h j := by
  have hε : ∀ i, |sgn χ i| ≤ 1 := fun i => (abs_sgn χ i).le
  have h1 := condExp_congr_ae (m := stageSigma n b j) (Zpot_ae_eq_Zproc hb hj χ)
  have h2 : (pointSampleLaw n)[Zproc (sgn χ) b h j | stageSigma n b j] = Zproc (sgn χ) b h j :=
    condExp_of_stronglyMeasurable (stageSigma_le n b j)
      (Zproc_stronglyMeasurable hb (sgn χ) h j) (integrable_Zproc hb (sgn χ) hε h j)
  rw [h2] at h1
  exact h1.trans (Zpot_ae_eq_Zproc hb hj χ).symm

/-- `E[Z_{j+1} | 𝓕_j]` is the average of `Z_{j+1}` over the next digits, almost surely. -/
lemma condExp_Zpot_succ {b h j : ℕ} (hb : 0 < b) (hj : j < h) (χ : Fin n → ℤˣ) :
    (pointSampleLaw n)[Zpot χ b h (j + 1) | stageSigma n b j] =ᵐ[pointSampleLaw n]
      Zmean (sgn χ) b h j :=
  (condExp_congr_ae (m := stageSigma n b j)
    (Zpot_ae_eq_Zproc hb (by omega : j + 1 ≤ h) χ)).trans
      (condExp_Zproc_succ hb hj (sgn χ) fun i => (abs_sgn χ i).le)

/-- The conditional gain is `E[Z_{j+1} | 𝓕_j] - Z_j`, almost surely. -/
lemma condExp_gain {b h j : ℕ} (hb : 0 < b) (hj : j < h) (χ : Fin n → ℤˣ) :
    (pointSampleLaw n)[fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P | stageSigma n b j]
      =ᵐ[pointSampleLaw n]
      fun P => ((pointSampleLaw n)[Zpot χ b h (j + 1) | stageSigma n b j]) P - Zpot χ b h j P := by
  have h1 := condExp_sub (integrable_Zpot hb (by omega : j + 1 ≤ h) χ)
    (integrable_Zpot hb hj.le χ) (stageSigma n b j)
  filter_upwards [h1, condExp_Zpot_self hb hj.le χ] with P hP hself
  have hP' : ((pointSampleLaw n)[Zpot χ b h (j + 1) - Zpot χ b h j | stageSigma n b j]) P =
      ((pointSampleLaw n)[Zpot χ b h (j + 1) | stageSigma n b j]) P -
        ((pointSampleLaw n)[Zpot χ b h j | stageSigma n b j]) P := hP
  rw [← hself, ← hP']
  rfl

/-- **"`Z_j` is `𝓕_j`-measurable"**: `Z_j` is almost surely equal to an `𝓕_j`-measurable
function, the potential read from the heights and the stage-`j` indices. (The equality holds
for all points with nonnegative coordinates, `Zpot_eq_Zstep`; for points outside the unit
square `F_χ` ignores the points with a negative coordinate, and the indices do not see this.) -/
theorem Zpot_aestronglyMeasurable {b h j : ℕ} (hb : 0 < b) (hj : j ≤ h) (χ : Fin n → ℤˣ) :
    AEStronglyMeasurable[stageSigma n b j] (Zpot χ b h j) (unifPts n) := by
  rw [← pointSampleLaw_eq_unifPts]
  exact ⟨Zproc (sgn χ) b h j, Zproc_stronglyMeasurable hb (sgn χ) h j,
    Zpot_ae_eq_Zproc hb hj χ⟩

/-! ### Lemma 2.4 -/

/-- **Lemma 2.4 (conditional gain).** For every `0 ≤ j < h`, almost surely

`E[Z_{j+1} - Z_j | 𝓕_j] ≥ δ_j = (1 / (4bM)) Σ_R √(m_R)`,

for every integer base `b ≥ 2` (the manuscript has `b ≥ 3`) and every coloring. -/
theorem lemma_2_4 {b h j : ℕ} (hb : 2 ≤ b) (hj : j < h) (χ : Fin n → ℤˣ) :
    ∀ᵐ P ∂unifPts n, delta b h j P ≤
      ((unifPts n)[fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P | stageSigma n b j]) P := by
  have hb0 : 0 < b := by omega
  have hgrid := ae_noGrid n b
  rw [← pointSampleLaw_eq_unifPts] at hgrid ⊢
  filter_upwards [condExp_gain hb0 hj χ, condExp_Zpot_succ hb0 hj χ,
    Zpot_ae_eq_Zproc hb0 hj.le χ, hgrid] with P h1 h2 h3 h4
  rw [h1, h2, h3, delta_eq_deltaStep hb0 h j P h4]
  have := Zmean_ge hb hj (sgn χ) (abs_sgn χ) P
  linarith

/-! ### The fluctuation term and display (10) -/

/-- **The fluctuation term** `T = Σ_{j<h} (Z_{j+1} - E[Z_{j+1} | 𝓕_j])` of display (10). -/
def fluct (χ : Fin n → ℤˣ) (b h : ℕ) (P : Fin n → ℝ × ℝ) : ℝ :=
  ∑ j ∈ Finset.range h,
    (Zpot χ b h (j + 1) P - ((unifPts n)[Zpot χ b h (j + 1) | stageSigma n b j]) P)

/-- **Display (10)**: `Z_h = Z_0 + Σ_{j<h} E[Z_{j+1} - Z_j | 𝓕_j] + T`, almost surely. -/
theorem roadmap {b : ℕ} (hb : 0 < b) (h : ℕ) (χ : Fin n → ℤˣ) :
    ∀ᵐ P ∂unifPts n, Zpot χ b h h P = Zpot χ b h 0 P +
      ∑ j ∈ Finset.range h,
        ((unifPts n)[fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P | stageSigma n b j]) P +
      fluct χ b h P := by
  have hall : ∀ᵐ P ∂pointSampleLaw n, ∀ j ∈ Finset.range h,
      ((pointSampleLaw n)[fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P | stageSigma n b j]) P =
        ((pointSampleLaw n)[Zpot χ b h (j + 1) | stageSigma n b j]) P - Zpot χ b h j P := by
    refine (ae_ball_iff (Finset.range h).countable_toSet).mpr fun j hj => ?_
    exact condExp_gain hb (Finset.mem_range.mp hj) χ
  unfold fluct
  rw [← pointSampleLaw_eq_unifPts]
  filter_upwards [hall] with P hP
  rw [Finset.sum_congr rfl hP, add_assoc, ← Finset.sum_add_distrib]
  have htel : ∑ j ∈ Finset.range h, (Zpot χ b h (j + 1) P - Zpot χ b h j P) =
      Zpot χ b h h P - Zpot χ b h 0 P :=
    Finset.sum_range_sub (fun j => Zpot χ b h j P) h
  have hcongr : ∑ j ∈ Finset.range h,
      (((pointSampleLaw n)[Zpot χ b h (j + 1) | stageSigma n b j]) P - Zpot χ b h j P +
        (Zpot χ b h (j + 1) P -
          ((pointSampleLaw n)[Zpot χ b h (j + 1) | stageSigma n b j]) P)) =
      ∑ j ∈ Finset.range h, (Zpot χ b h (j + 1) P - Zpot χ b h j P) :=
    Finset.sum_congr rfl fun j _ => by ring
  rw [hcongr, htel]
  ring

end

end R56Audit
