import Oscillation

/-!
# The next digits are independent and uniform given the heights and the earlier digits

Auditor's supplement (not part of the audited archive).

Section 2.4: "Let `𝓕_j` be the σ-field generated by all heights and by the first `j` base-`b`
digits of every horizontal coordinate. \[…\] The `(j+1)`-st digits, which we call the next
digits at stage `j`, are independent and uniform conditional on `𝓕_j`."

`condExp_fresh_given_heights` is this statement for `n` independent uniform points of the
unit square, in the form: the conditional expectation of a bounded measurable function of
the heights, the cell indices at resolution `k` and the next digits (base `m`), given the
heights and the cell indices, is the uniform average over the next digits.

The archive has the corresponding statement for the horizontal coordinates alone
(`Riesz.condExp_freshGrid_with_past`), with the heights replaced by fixed labels.
-/

namespace R56Audit

open MeasureTheory Riesz Riesz.PointSets Oscillation

noncomputable section

/-- The heights of the points, and the indices of the cells `(c/k, (c+1)/k]` that contain
their horizontal coordinates. -/
def coarseInfo (n k : ℕ) (P : Fin n → ℝ × ℝ) : (Fin n → ℝ) × (Fin n → ℤ) :=
  (fun i => (P i).2, fun i => gridIndex k (P i).1)

lemma measurable_coarseInfo (n k : ℕ) : Measurable (coarseInfo n k) := by
  refine Measurable.prodMk (measurable_pi_iff.mpr fun i => ?_) (measurable_pi_iff.mpr fun i => ?_)
  · exact measurable_snd.comp (measurable_pi_apply i)
  · exact (measurable_gridIndex k).comp (measurable_fst.comp (measurable_pi_apply i))

/-- The next digits in base `m`, after the cell indices at resolution `k`. -/
def freshInfo (n k m : ℕ) (hm : 0 < m) (P : Fin n → ℝ × ℝ) : Fin n → Fin m :=
  fun i => freshGridIndex k m hm (P i).1

lemma measurable_freshInfo (n k m : ℕ) (hm : 0 < m) : Measurable (freshInfo n k m hm) := by
  refine measurable_pi_iff.mpr fun i => ?_
  exact (measurable_freshGridIndex k m hm).comp (measurable_fst.comp (measurable_pi_apply i))

/-!
### Proof of the conditional law

For fixed heights, only the horizontal coordinates are integrated, and the archive's theorem
for the horizontal coordinates applies (`integral_fresh_eq_integral_finAvg`). Integrating
over the heights gives the statement in integrated form (`integral_fresh_given_heights`).
Applied to the function cut off outside an event of the conditioning σ-algebra, this is the
characterization of the conditional expectation.
-/

/-- The coarse information of the points `(U i, V i)`: the heights `V`, the cell indices of `U`. -/
lemma coarseInfo_pair (n k : ℕ) (U V : Fin n → ℝ) :
    coarseInfo n k (fun i => (U i, V i)) = (V, sampleGridIndex n k U) := rfl

/-- The next digits of the points `(U i, V i)` are those of the horizontal coordinates `U`. -/
lemma freshInfo_pair (n k m : ℕ) (hm : 0 < m) (U V : Fin n → ℝ) :
    freshInfo n k m hm (fun i => (U i, V i)) = sampleFreshIndex n k m hm U := rfl

/-- The uniform average over the `m ^ n` vectors of `n` digits in base `m`. -/
lemma finAvg_digits (n m : ℕ) (f : (Fin n → Fin m) → ℝ) :
    finAvg f = (∑ a, f a) / (m : ℝ) ^ n := by
  simp [finAvg]

/-- Horizontal coordinates alone: under the integral, a bounded function of the cell indices
and the next digits may be replaced by its uniform average over the next digits. -/
lemma integral_fresh_eq_integral_finAvg (n k m : ℕ) (hk : 0 < k) (hm : 0 < m)
    (G : (Fin n → ℤ) → (Fin n → Fin m) → ℝ) (K : ℝ) (hG : ∀ c a, |G c a| ≤ K) :
    ∫ U, G (sampleGridIndex n k U) (sampleFreshIndex n k m hm U) ∂coordinateSampleLaw n =
      ∫ U, finAvg (fun a => G (sampleGridIndex n k U) a) ∂coordinateSampleLaw n := by
  have hmeas : Measurable (fun U => G (sampleGridIndex n k U) (sampleFreshIndex n k m hm U)) :=
    (measurable_of_countable (fun z : (Fin n → ℤ) × (Fin n → Fin m) => G z.1 z.2)).comp
      ((measurable_sampleGridIndex n k).prodMk (measurable_sampleFreshIndex n k m hm))
  have hint : Integrable (fun U => G (sampleGridIndex n k U) (sampleFreshIndex n k m hm U))
      (coordinateSampleLaw n) :=
    Integrable.of_bound hmeas.aestronglyMeasurable K (Filter.Eventually.of_forall fun _ => hG _ _)
  calc ∫ U, G (sampleGridIndex n k U) (sampleFreshIndex n k m hm U) ∂coordinateSampleLaw n
      = ∫ U, ((coordinateSampleLaw n)[fun U =>
          G (sampleGridIndex n k U) (sampleFreshIndex n k m hm U) | sampleGridSigma n k]) U
          ∂coordinateSampleLaw n :=
        (integral_condExp (measurable_sampleGridIndex n k).comap_le).symm
    _ = ∫ U, (∑ a, G (sampleGridIndex n k U) a) / (m : ℝ) ^ n ∂coordinateSampleLaw n :=
        integral_congr_ae (condExp_freshGrid_with_past n k m hk hm G hint)
    _ = ∫ U, finAvg (fun a => G (sampleGridIndex n k U) a) ∂coordinateSampleLaw n := by
        simp only [finAvg_digits]

/-- A function of the coarse information and the next digits, measurable in the former, is
measurable: the next digits take finitely many values. -/
lemma measurable_coarse_fresh (n k m : ℕ) (hm : 0 < m)
    (H : (Fin n → ℝ) × (Fin n → ℤ) → (Fin n → Fin m) → ℝ)
    (hH : ∀ r, Measurable (fun p => H p r)) :
    Measurable (fun P => H (coarseInfo n k P) (freshInfo n k m hm P)) :=
  (measurable_from_prod_countable_left
      (f := fun z : ((Fin n → ℝ) × (Fin n → ℤ)) × (Fin n → Fin m) => H z.1 z.2) hH).comp
    ((measurable_coarseInfo n k).prodMk (measurable_freshInfo n k m hm))

/-- A bounded function of the coarse information and of the next digits is integrable. -/
lemma integrable_coarse_fresh (n k m : ℕ) (hm : 0 < m)
    (H : (Fin n → ℝ) × (Fin n → ℤ) → (Fin n → Fin m) → ℝ)
    (hH : ∀ r, Measurable (fun p => H p r))
    (K : ℝ) (hK : ∀ p r, |H p r| ≤ K) :
    Integrable (fun P => H (coarseInfo n k P) (freshInfo n k m hm P)) (pointSampleLaw n) :=
  Integrable.of_bound (measurable_coarse_fresh n k m hm H hH).aestronglyMeasurable K
    (Filter.Eventually.of_forall fun _ => hK _ _)

/-- The average over the next digits is a measurable function of the coarse information. -/
lemma measurable_finAvg_coarse (n m : ℕ)
    (H : (Fin n → ℝ) × (Fin n → ℤ) → (Fin n → Fin m) → ℝ)
    (hH : ∀ r, Measurable (fun p => H p r)) :
    Measurable (fun p => finAvg (fun r => H p r)) :=
  (Finset.measurable_sum _ fun r _ => hH r).div_const _

/-- The average over the next digits of a bounded function is integrable. -/
lemma integrable_finAvg_coarse (n k m : ℕ)
    (H : (Fin n → ℝ) × (Fin n → ℤ) → (Fin n → Fin m) → ℝ)
    (hH : ∀ r, Measurable (fun p => H p r))
    (K : ℝ) (hK : ∀ p r, |H p r| ≤ K) :
    Integrable (fun P => finAvg (fun r => H (coarseInfo n k P) r)) (pointSampleLaw n) :=
  (integrable_finsetSum _ fun r _ => Integrable.of_bound
    ((hH r).comp (measurable_coarseInfo n k)).aestronglyMeasurable K
    (Filter.Eventually.of_forall fun _ => hK _ r)).div_const _

/-- Integrated form: under the integral, a bounded function of the coarse information and the
next digits may be replaced by its uniform average over the next digits. -/
lemma integral_fresh_given_heights (n k m : ℕ) (hk : 0 < k) (hm : 0 < m)
    (H : (Fin n → ℝ) × (Fin n → ℤ) → (Fin n → Fin m) → ℝ)
    (hH : ∀ r, Measurable (fun p => H p r))
    (K : ℝ) (hK : ∀ p r, |H p r| ≤ K) :
    ∫ P, H (coarseInfo n k P) (freshInfo n k m hm P) ∂pointSampleLaw n =
      ∫ P, finAvg (fun r => H (coarseInfo n k P) r) ∂pointSampleLaw n := by
  -- integrate the horizontal coordinates `U` first, for fixed heights `V`
  rw [integral_point_eq_vertical_horizontal _ (integrable_coarse_fresh n k m hm H hH K hK),
    integral_point_eq_vertical_horizontal _ (integrable_finAvg_coarse n k m H hH K hK)]
  refine integral_congr_ae (Filter.Eventually.of_forall fun V => ?_)
  simp only [coarseInfo_pair, freshInfo_pair]
  exact integral_fresh_eq_integral_finAvg n k m hk hm (fun c a => H (V, c) a) K
    fun c a => hK (V, c) a

/-- **The next digits are independent and uniform conditional on the heights and the earlier
digits.** For a bounded function `H` of the heights and cell indices `p` and of the next
digits `r`, measurable in `p`,

`E[H(p, r) | heights, cell indices] = (average of H(p, ·) over all values of the next digits)`

almost surely, for `n` independent uniform points of `[0,1]²`. -/
theorem condExp_fresh_given_heights (n k m : ℕ) (hk : 0 < k) (hm : 0 < m)
    (H : (Fin n → ℝ) × (Fin n → ℤ) → (Fin n → Fin m) → ℝ)
    (hH : ∀ r, Measurable (fun p => H p r))
    (K : ℝ) (hK : ∀ p r, |H p r| ≤ K) :
    (pointSampleLaw n)[fun P => H (coarseInfo n k P) (freshInfo n k m hm P) |
        MeasurableSpace.comap (coarseInfo n k) inferInstance] =ᵐ[pointSampleLaw n]
      fun P => finAvg (fun r => H (coarseInfo n k P) r) := by
  have hc : Measurable (coarseInfo n k) := measurable_coarseInfo n k
  -- uniqueness of the conditional expectation: compare the integrals over the events of the
  -- conditioning σ-algebra
  refine (ae_eq_condExp_of_forall_setIntegral_eq hc.comap_le
    (integrable_coarse_fresh n k m hm H hH K hK)
    (fun s _ _ => (integrable_finAvg_coarse n k m H hH K hK).integrableOn) ?_ ?_).symm
  · -- such an event is `coarseInfo n k P ∈ S` for a measurable set `S`
    rintro s ⟨S, hS, rfl⟩ -
    -- the integrated form, for `H` cut off outside `S`
    have hcut := integral_fresh_given_heights n k m hk hm
      (fun p r => S.indicator (fun q => H q r) p) (fun r => (hH r).indicator hS) K
      (fun p r => (norm_indicator_le_norm_self (fun q => H q r) p).trans (hK p r))
    calc ∫ P in coarseInfo n k ⁻¹' S, finAvg (fun r => H (coarseInfo n k P) r) ∂pointSampleLaw n
        = ∫ P, finAvg (fun r => S.indicator (fun q => H q r) (coarseInfo n k P))
            ∂pointSampleLaw n := by
          rw [← integral_indicator (hc hS)]
          refine integral_congr_ae (Filter.Eventually.of_forall fun P => ?_)
          by_cases hP : coarseInfo n k P ∈ S <;> simp [hP, finAvg]
      _ = ∫ P, S.indicator (fun q => H q (freshInfo n k m hm P)) (coarseInfo n k P)
            ∂pointSampleLaw n := hcut.symm
      _ = ∫ P in coarseInfo n k ⁻¹' S, H (coarseInfo n k P) (freshInfo n k m hm P)
            ∂pointSampleLaw n := by
          rw [← integral_indicator (hc hS)]
          refine integral_congr_ae (Filter.Eventually.of_forall fun P => ?_)
          by_cases hP : coarseInfo n k P ∈ S <;> simp [hP]
  · -- the average is a measurable function of the coarse information
    exact ((measurable_finAvg_coarse n m H hH).comp
      (comap_measurable (coarseInfo n k))).stronglyMeasurable.aestronglyMeasurable

end

end R56Audit
