import Oscillation
import Mathlib.MeasureTheory.Function.FactorsThrough

/-!
# Conditional expectations given random elements that determine each other almost surely

Auditor's supplement (not part of the audited archive).

A σ-field of the manuscript is described by its generators ("the σ-field generated by all
heights and by the first `j` base-`b` digits of every horizontal coordinate"), and the same
information can be encoded by other random elements ("The first `j` digits of `U_i` determine
the stage-`j` horizontal interval that contains `U_i`."). On the probability-one event of
Section 2.1 the two encodings determine each other. `condExp_comap_congr_ae` says that
conditional expectations do not see the difference.
-/

namespace R56Audit

open MeasureTheory

noncomputable section

/-- **Almost surely equivalent generators give the same conditional expectations.** If
`f₂ = e ∘ f₁` and `f₁ = e' ∘ f₂` almost surely, with `e`, `e'` measurable, then conditional
expectations given `f₁` and given `f₂` agree almost surely. -/
theorem condExp_comap_congr_ae {Ω α β : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    [MeasurableSpace β] {μ : Measure Ω} [IsFiniteMeasure μ] {f₁ : Ω → α} {f₂ : Ω → β}
    (hf₁ : Measurable f₁) (hf₂ : Measurable f₂) {e : α → β} {e' : β → α} (he : Measurable e)
    (he' : Measurable e') (h₁₂ : f₂ =ᵐ[μ] e ∘ f₁) (h₂₁ : f₁ =ᵐ[μ] e' ∘ f₂) (X : Ω → ℝ) :
    μ[X | MeasurableSpace.comap f₁ inferInstance] =ᵐ[μ]
      μ[X | MeasurableSpace.comap f₂ inferInstance] := by
  by_cases hX : Integrable X μ
  swap
  · rw [condExp_of_not_integrable hX, condExp_of_not_integrable hX]
  refine ae_eq_condExp_of_forall_setIntegral_eq hf₂.comap_le hX
    (fun s _ _ => integrable_condExp.integrableOn) (fun s hs _ => ?_) ?_
  · -- an event of `f₂` is almost surely an event of `f₁`
    obtain ⟨B, hB, rfl⟩ := hs
    have hset : f₂ ⁻¹' B =ᵐ[μ] f₁ ⁻¹' (e ⁻¹' B) := by
      filter_upwards [h₁₂] with ω hω
      change (f₂ ω ∈ B) = (e (f₁ ω) ∈ B)
      rw [hω]
      rfl
    rw [setIntegral_congr_set hset, setIntegral_congr_set hset]
    exact setIntegral_condExp hf₁.comap_le hX ⟨e ⁻¹' B, he hB, rfl⟩
  · -- a function of `f₁` is almost surely a function of `f₂` (Doob–Dynkin)
    have hsm : StronglyMeasurable[MeasurableSpace.comap f₁ inferInstance]
        (μ[X | MeasurableSpace.comap f₁ inferInstance]) := stronglyMeasurable_condExp
    obtain ⟨φ, hφ, hφeq⟩ := StronglyMeasurable.exists_eq_measurable_comp hsm
    refine ⟨fun ω => φ (e' (f₂ ω)),
      (hφ.comp_measurable he').comp_measurable (comap_measurable f₂), ?_⟩
    filter_upwards [h₂₁] with ω hω
    rw [hφeq]
    change φ (f₁ ω) = φ (e' (f₂ ω))
    rw [hω]
    rfl

end

end R56Audit
