import R56Audit.Fluctuations
import R56Audit.CondExpGenerators

/-!
# The σ-field generated by the heights and the first `j` digits

Auditor's supplement (not part of the audited archive).

Section 2.4: "Let `𝓕_j` be the σ-field generated by all heights and by the first `j` base-`b`
digits of every horizontal coordinate. The first `j` digits of `U_i` determine the stage-`j`
horizontal interval that contains `U_i`."

`StageFiltration.lean` takes for `𝓕_j` the σ-field `stageSigma n b j` generated by the heights
and by the index of the stage-`j` interval `(c b^{-j}, (c+1) b^{-j}]` that contains each
`U_i`. This file defines the base-`b` digits themselves (`digit b k u = ⌊b^k u⌋ mod b`) and
the σ-field `digitSigma n b j` generated by all heights and the first `j` digits of every
horizontal coordinate, and proves that the difference is invisible:

* `fresh_eq_digit`: for a positive number that is not of the form `m/b^r`, the next digit at
  stage `k` (the index of the child of its stage-`k` interval that contains it) is its
  `(k+1)`-st base-`b` digit;
* `coarseInfo_ae_eq_digitInfo`, `digitInfo_ae_eq_coarseInfo`: almost surely, the heights and
  the stage-`j` indices are a measurable function of the heights and the first `j` digits, and
  conversely;
* `condExp_digitSigma`: conditional expectations given `digitSigma n b j` and given
  `stageSigma n b j` are almost surely equal;
* `lemma_2_4_digits`, `lemma_2_6_digits`: Lemmas 2.4 and 2.6 with the σ-fields of the digits;
* `roadmap_digits`: display (10) with the σ-fields of the digits;
* `Zpot_aestronglyMeasurable_digits`: "So `Z_j` is `𝓕_j`-measurable", for the σ-field of the
  digits: `Z_j` is almost surely equal to a `digitSigma n b j`-measurable function;
* `nextDigits`, `condExp_nextDigits`: "The `(j+1)`-st digits, which we call the next digits at
  stage `j`, are independent and uniform conditional on `𝓕_j`", for the σ-field of the digits:
  the conditional expectation, given `digitSigma n b j`, of a bounded function of the heights,
  the first `j` digits and the next digits is its average over all values of the next digits.
-/

namespace R56Audit

open MeasureTheory Riesz Riesz.PointSets Oscillation

noncomputable section

variable {n : ℕ}

/-- The `k`-th base-`b` digit of `u`, for `k ≥ 1`: `⌊b^k u⌋ mod b`. For `u ∈ [0,1)` these are
the digits of the expansion `u = Σ_{k ≥ 1} d_k b^{-k}`. -/
def digit (b k : ℕ) (u : ℝ) : ℕ := ⌊(b : ℝ) ^ k * u⌋₊ % b

/-- All heights, and the first `j` base-`b` digits of every horizontal coordinate. -/
def digitInfo (n b j : ℕ) (P : Fin n → ℝ × ℝ) : (Fin n → ℝ) × (Fin n → Fin j → ℕ) :=
  (fun i => (P i).2, fun i k => digit b ((k : ℕ) + 1) (P i).1)

/-- The σ-field generated by all heights and by the first `j` base-`b` digits of every
horizontal coordinate. -/
abbrev digitSigma (n b j : ℕ) : MeasurableSpace (Fin n → ℝ × ℝ) :=
  MeasurableSpace.comap (digitInfo n b j) inferInstance

/-- Every digit is a measurable function of the number. -/
lemma measurable_digit (b k : ℕ) : Measurable (digit b k) :=
  (measurable_of_countable fun m : ℕ => m % b).comp
    (measurable_const.mul measurable_id).nat_floor

lemma measurable_digitInfo (n b j : ℕ) : Measurable (digitInfo n b j) := by
  refine Measurable.prodMk (measurable_pi_iff.mpr fun i => ?_)
    (measurable_pi_iff.mpr fun i => measurable_pi_iff.mpr fun k => ?_)
  · exact measurable_snd.comp (measurable_pi_apply i)
  · exact (measurable_digit b ((k : ℕ) + 1)).comp (measurable_fst.comp (measurable_pi_apply i))

/-- For a positive number that is not of the form `m/b^r`, the next digit at stage `k` is the
`(k+1)`-st base-`b` digit. -/
theorem fresh_eq_digit {b : ℕ} (hb : 0 < b) (k : ℕ) {u : ℝ} (hu : 0 < u)
    (hgrid : ∀ (m : ℤ) (r : ℕ), u ≠ (m : ℝ) / (b : ℝ) ^ r) :
    (freshGridIndex (b ^ k) b hb u : ℕ) = digit b (k + 1) u := by
  have hpow : (0 : ℝ) < (b : ℝ) ^ (k + 1) := pow_pos (Nat.cast_pos.mpr hb) _
  -- `b^(k+1) u` is not an integer, so its ceiling is its floor plus one
  have hceil : ⌈(b : ℝ) ^ (k + 1) * u⌉ = ⌊(b : ℝ) ^ (k + 1) * u⌋ + 1 := by
    rw [Int.ceil_eq_floor_add_one_iff_notMem]
    rintro ⟨m, hm⟩
    refine hgrid m (k + 1) ?_
    rw [hm]
    exact (mul_div_cancel_left₀ u hpow.ne').symm
  -- hence the index of the stage-`(k+1)` interval that contains `u` is `⌊b^(k+1) u⌋`
  have hidx : gridIndex (b ^ k * b) u = ⌊(b : ℝ) ^ (k + 1) * u⌋ := by
    unfold gridIndex
    rw [Nat.cast_mul, Nat.cast_pow, ← pow_succ, hceil, add_sub_cancel_right]
  -- the next digit is the remainder of this index modulo `b`; compare the two sides in `ℤ`
  apply Nat.cast_injective (R := ℤ)
  rw [freshGridIndex_eq_emod (b ^ k) b (pow_pos hb k) hb u, hidx, digit, Int.natCast_emod,
    Int.natCast_floor_eq_floor (mul_pos hpow hu).le]

/-- The integer whose base-`b` expansion consists of the digits `d 0, …, d (j - 1)`, the most
significant digit first: `Σ_{k < j} b^(j-(k+1)) d_k`. -/
def idxOfDigits (b j : ℕ) (d : Fin j → ℕ) : ℤ :=
  ∑ k : Fin j, (b : ℤ) ^ (j - ((k : ℕ) + 1)) * (d k : ℤ)

/-- The integer with the digits `d 0, …, d j` is `b` times the integer with the digits
`d 0, …, d (j - 1)`, plus the last digit `d j`. -/
lemma idxOfDigits_succ (b j : ℕ) (d : Fin (j + 1) → ℕ) :
    idxOfDigits b (j + 1) d =
      (b : ℤ) * idxOfDigits b j (fun k => d k.castSucc) + (d (Fin.last j) : ℤ) := by
  unfold idxOfDigits
  rw [Fin.sum_univ_castSucc, Finset.mul_sum]
  congr 1
  · refine Finset.sum_congr rfl fun k _ => ?_
    rw [Fin.val_castSucc, Nat.sub_add_comm (Nat.succ_le_of_lt k.isLt), pow_succ', mul_assoc]
  · rw [Fin.val_last, Nat.sub_self, pow_zero, one_mul]

/-- "The first `j` digits of `U_i` determine the stage-`j` horizontal interval that contains
`U_i`": for a number of `(0,1]` that is not of the form `m/b^r`, the index of its stage-`j`
interval is the integer whose base-`b` expansion consists of its first `j` digits. -/
lemma gridIndex_eq_idxOfDigits {b : ℕ} (hb : 0 < b) (j : ℕ) {u : ℝ}
    (hu : u ∈ Set.Ioc (0 : ℝ) 1) (hgrid : ∀ (m : ℤ) (r : ℕ), u ≠ (m : ℝ) / (b : ℝ) ^ r) :
    gridIndex (b ^ j) u = idxOfDigits b j (fun k => digit b ((k : ℕ) + 1) u) := by
  induction j with
  | zero =>
    -- the only interval of stage `0` is `(0, 1]`, with index `0`
    have h := gridIndex_bounds 1 one_pos hu
    have h0 : (0 : ℤ) ≤ gridIndex 1 u := by exact_mod_cast h.1
    have h1 : gridIndex 1 u + 1 ≤ 1 := by exact_mod_cast h.2
    rw [pow_zero, idxOfDigits, Fin.sum_univ_zero]
    omega
  | succ j ih =>
    -- the index of stage `j + 1` is `b` times the index of stage `j` plus the next digit
    rw [gridIndex_succ hb, ih, fresh_eq_digit hb j hu.1 hgrid, idxOfDigits_succ b j]
    rfl

/-- The last `j` base-`b` digits of the integer `g`, the most significant digit first: the
entry `k` is the digit of weight `b^(j-(k+1))`. -/
def digitsOfIdx (b j : ℕ) (g : ℤ) (k : Fin j) : ℕ :=
  ((g / (b : ℤ) ^ (j - ((k : ℕ) + 1))) % (b : ℤ)).toNat

/-- Conversely, the stage-`j` interval determines the first `j` digits: for a positive number
that is not of the form `m/b^r`, the first `j` digits are the base-`b` digits of the index of
its stage-`j` interval. -/
lemma digit_eq_digitsOfIdx {b : ℕ} (hb : 0 < b) (j : ℕ) {u : ℝ} (hu : 0 < u)
    (hgrid : ∀ (m : ℤ) (r : ℕ), u ≠ (m : ℝ) / (b : ℝ) ^ r) (k : Fin j) :
    digit b ((k : ℕ) + 1) u = digitsOfIdx b j (gridIndex (b ^ j) u) k := by
  -- the quotient of the stage-`j` index by `b^(j-(k+1))` is the stage-`(k+1)` index
  have h1 := gridIndex_mul_ediv (b ^ ((k : ℕ) + 1)) (b ^ (j - ((k : ℕ) + 1))) (pow_pos hb _) u
  rw [pow_mul_pow_sub b (Nat.succ_le_of_lt k.isLt), Nat.cast_pow] at h1
  -- and the remainder of the stage-`(k+1)` index modulo `b` is the next digit at stage `k`
  have h2 := freshGridIndex_eq_emod (b ^ (k : ℕ)) b (pow_pos hb _) hb u
  rw [← pow_succ] at h2
  rw [digitsOfIdx, h1, ← h2, Int.toNat_natCast, fresh_eq_digit hb k hu hgrid]

/-- The heights and the stage-`j` indices, read from the heights and the first `j` digits: the
heights are kept, and the index of a point is the integer whose base-`b` expansion consists of
its first `j` digits. -/
def coarseOfDigits (n b j : ℕ) (p : (Fin n → ℝ) × (Fin n → Fin j → ℕ)) :
    (Fin n → ℝ) × (Fin n → ℤ) :=
  (p.1, fun i => idxOfDigits b j (p.2 i))

/-- The heights and the first `j` digits, read from the heights and the stage-`j` indices: the
heights are kept, and the digits of a point are the last `j` base-`b` digits of its index. -/
def digitsOfCoarse (n b j : ℕ) (p : (Fin n → ℝ) × (Fin n → ℤ)) :
    (Fin n → ℝ) × (Fin n → Fin j → ℕ) :=
  (p.1, fun i => digitsOfIdx b j (p.2 i))

/-- The indices are a measurable function of the digits; the heights are kept. -/
lemma measurable_coarseOfDigits (n b j : ℕ) : Measurable (coarseOfDigits n b j) :=
  measurable_fst.prodMk ((measurable_of_countable
    (fun d : Fin n → Fin j → ℕ => fun i => idxOfDigits b j (d i))).comp measurable_snd)

/-- The digits are a measurable function of the indices; the heights are kept. -/
lemma measurable_digitsOfCoarse (n b j : ℕ) : Measurable (digitsOfCoarse n b j) :=
  measurable_fst.prodMk ((measurable_of_countable
    (fun g : Fin n → ℤ => fun i => digitsOfIdx b j (g i))).comp measurable_snd)

/-- "The first `j` digits of `U_i` determine the stage-`j` horizontal interval that contains
`U_i`", for all points at once: almost surely, the heights and the stage-`j` indices are the
function `coarseOfDigits` of the heights and the first `j` digits. -/
theorem coarseInfo_ae_eq_digitInfo {b : ℕ} (hb : 0 < b) (n j : ℕ) :
    coarseInfo n (b ^ j) =ᵐ[unifPts n] coarseOfDigits n b j ∘ digitInfo n b j := by
  -- the digits determine the indices, on the probability-one event of Section 2.1
  filter_upwards [ae_inUnit n, ae_noGrid n b] with P hP hgrid
  exact Prod.ext rfl (funext fun i =>
    gridIndex_eq_idxOfDigits hb j (hP i).1 fun m r => (hgrid i m r).1)

/-- Conversely, the stage-`j` intervals determine the first `j` digits: almost surely, the
heights and the first `j` digits are the function `digitsOfCoarse` of the heights and the
stage-`j` indices. -/
theorem digitInfo_ae_eq_coarseInfo {b : ℕ} (hb : 0 < b) (n j : ℕ) :
    digitInfo n b j =ᵐ[unifPts n] digitsOfCoarse n b j ∘ coarseInfo n (b ^ j) := by
  -- the indices determine the digits, on the probability-one event of Section 2.1
  filter_upwards [ae_inUnit n, ae_noGrid n b] with P hP hgrid
  exact Prod.ext rfl (funext fun i => funext fun k =>
    digit_eq_digitsOfIdx hb j (hP i).1.1 (fun m r => (hgrid i m r).1) k)

/-- **The two descriptions of `𝓕_j` give the same conditional expectations**, almost surely:
the σ-field generated by the heights and the first `j` digits, and the σ-field generated by
the heights and the stage-`j` indices. -/
theorem condExp_digitSigma {b : ℕ} (hb : 0 < b) (j : ℕ) (f : (Fin n → ℝ × ℝ) → ℝ) :
    (unifPts n)[f | digitSigma n b j] =ᵐ[unifPts n] (unifPts n)[f | stageSigma n b j] :=
  -- almost surely, the indices are a measurable function of the digits and the digits are a
  -- measurable function of the indices; the heights are kept
  condExp_comap_congr_ae (measurable_digitInfo n b j) (measurable_coarseInfo n (b ^ j))
    (measurable_coarseOfDigits n b j) (measurable_digitsOfCoarse n b j)
    (coarseInfo_ae_eq_digitInfo hb n j) (digitInfo_ae_eq_coarseInfo hb n j) f

/-- **Lemma 2.4** with `𝓕_j` generated by all heights and by the first `j` base-`b` digits of
every horizontal coordinate. -/
theorem lemma_2_4_digits {b h j : ℕ} (hb : 2 ≤ b) (hj : j < h) (χ : Fin n → ℤˣ) :
    ∀ᵐ P ∂unifPts n, delta b h j P ≤
      ((unifPts n)[fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P | digitSigma n b j]) P := by
  have hb0 : 0 < b := by omega
  -- Lemma 2.4 for the stage-`j` indices; the conditional expectation is almost surely the same
  filter_upwards [lemma_2_4 hb hj χ, condExp_digitSigma hb0 j
    (fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P)] with P hP hdig
  exact hP.trans_eq hdig.symm

/-- The fluctuation term `T` of display (10), with `𝓕_j` generated by the heights and the
first `j` digits. -/
def fluctDigits (χ : Fin n → ℤˣ) (b h : ℕ) (P : Fin n → ℝ × ℝ) : ℝ :=
  ∑ j ∈ Finset.range h,
    (Zpot χ b h (j + 1) P - ((unifPts n)[Zpot χ b h (j + 1) | digitSigma n b j]) P)

/-- Almost surely, the two versions of the fluctuation term agree. -/
theorem fluctDigits_ae_eq {b : ℕ} (hb : 0 < b) (h : ℕ) (χ : Fin n → ℤˣ) :
    fluctDigits χ b h =ᵐ[unifPts n] fluct χ b h := by
  -- almost surely, the conditional expectations of all `h` transitions agree
  have hall : ∀ᵐ P ∂unifPts n, ∀ j ∈ Finset.range h,
      ((unifPts n)[Zpot χ b h (j + 1) | digitSigma n b j]) P =
        ((unifPts n)[Zpot χ b h (j + 1) | stageSigma n b j]) P :=
    (ae_ball_iff (Finset.range h).countable_toSet).mpr fun j _ =>
      condExp_digitSigma hb j (Zpot χ b h (j + 1))
  filter_upwards [hall] with P hP
  unfold fluctDigits fluct
  exact Finset.sum_congr rfl fun j hj => by rw [hP j hj]

/-- **Lemma 2.6** with `𝓕_j` generated by all heights and by the first `j` base-`b` digits of
every horizontal coordinate. -/
theorem lemma_2_6_digits {b : ℕ} (hb : 0 < b) (h : ℕ) (χ : Fin n → ℤˣ) {lam : ℝ}
    (hlam : 0 < lam) :
    (unifPts n).real {P | fluctDigits χ b h P ≤ -lam} ≤
      Real.exp (-(lam ^ 2 * ((b : ℝ) ^ (h - 1)) ^ 2 / (2 * h * n))) := by
  -- the events for the two versions of the fluctuation term differ by a null set
  have hsets : {P | fluctDigits χ b h P ≤ -lam} =ᵐ[unifPts n] {P | fluct χ b h P ≤ -lam} := by
    filter_upwards [fluctDigits_ae_eq hb h χ] with P hP
    rw [hP]
  rw [measureReal_congr hsets]
  exact lemma_2_6 hb h χ hlam

/-! ### Display (10), "`Z_j` is `𝓕_j`-measurable", and the next digits -/

/-- **Display (10)** with `𝓕_j` generated by all heights and the first `j` digits. -/
theorem roadmap_digits {b : ℕ} (hb : 0 < b) (h : ℕ) (χ : Fin n → ℤˣ) :
    ∀ᵐ P ∂unifPts n, Zpot χ b h h P = Zpot χ b h 0 P +
      ∑ j ∈ Finset.range h,
        ((unifPts n)[fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P | digitSigma n b j]) P +
      fluctDigits χ b h P := by
  -- almost surely, the conditional gains of all `h` transitions agree
  have hall : ∀ᵐ P ∂unifPts n, ∀ j ∈ Finset.range h,
      ((unifPts n)[fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P | digitSigma n b j]) P =
        ((unifPts n)[fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P | stageSigma n b j]) P :=
    (ae_ball_iff (Finset.range h).countable_toSet).mpr fun j _ =>
      condExp_digitSigma hb j fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P
  -- display (10) for the stage-`j` indices; the fluctuation terms agree almost surely
  filter_upwards [roadmap hb h χ, hall, fluctDigits_ae_eq hb h χ] with P hP hgain hfluct
  rw [Finset.sum_congr rfl hgain, hfluct]
  exact hP

/-- "So `Z_j` is `𝓕_j`-measurable": `Z_j` is almost surely equal to a function that is measurable
with respect to the σ-field generated by all heights and the first `j` digits. (The function
is the potential read from the heights and the stage-`j` indices, with the indices read from
the digits. It is `Z_j` whenever all coordinates lie in `(0,1]` and no horizontal coordinate
has the form `m/b^r`.) -/
theorem Zpot_aestronglyMeasurable_digits {b h j : ℕ} (hb : 0 < b) (hj : j ≤ h) (χ : Fin n → ℤˣ) :
    AEStronglyMeasurable[digitSigma n b j] (Zpot χ b h j) (unifPts n) := by
  -- the potential read from the heights and the indices, the indices read from the digits:
  -- a measurable function of the heights and the first `j` digits
  have hmeas : Measurable[digitSigma n b j] (fun P : Fin n → ℝ × ℝ =>
      Zstep (sgn χ) b h j (coarseOfDigits n b j (digitInfo n b j P)).1
        (coarseOfDigits n b j (digitInfo n b j P)).2) :=
    ((measurable_Zstep_uncurry hb (sgn χ) h j).comp (measurable_coarseOfDigits n b j)).comp
      (comap_measurable (digitInfo n b j))
  refine ⟨_, hmeas.stronglyMeasurable, ?_⟩
  -- almost surely, this is `Z_j`: the digits determine the indices
  have hZ := Zpot_ae_eq_Zproc hb hj χ
  rw [pointSampleLaw_eq_unifPts] at hZ
  filter_upwards [hZ, coarseInfo_ae_eq_digitInfo hb n j] with P hP hc
  rw [hP, Zproc_eq hj, hc]
  rfl

/-- The next digits at stage `j`: the `(j+1)`-st base-`b` digits of the horizontal coordinates. -/
def nextDigits {b : ℕ} (hb : 0 < b) (n j : ℕ) (P : Fin n → ℝ × ℝ) : Fin n → Fin b :=
  fun i => ⟨digit b (j + 1) (P i).1, Nat.mod_lt _ hb⟩

/-- The next digits are a measurable function of the sample. -/
lemma measurable_nextDigits {b : ℕ} (hb : 0 < b) (n j : ℕ) : Measurable (nextDigits hb n j) := by
  refine measurable_pi_iff.mpr fun i => ?_
  -- a digit is the remainder modulo `b` of an integer part
  have hmod : Measurable (fun m : ℕ => (⟨m % b, Nat.mod_lt m hb⟩ : Fin b)) :=
    measurable_of_countable _
  have hfloor : Measurable (fun u : ℝ => ⌊(b : ℝ) ^ (j + 1) * u⌋₊) :=
    (measurable_const.mul measurable_id).nat_floor
  exact (hmod.comp hfloor).comp (measurable_fst.comp (measurable_pi_apply i))

/-- Almost surely, the next digit of every point at stage `j` is the index of the child of its
stage-`j` interval that contains it (`fresh_eq_digit`). -/
theorem nextDigits_ae_eq_freshInfo {b : ℕ} (hb : 0 < b) (n j : ℕ) :
    nextDigits hb n j =ᵐ[unifPts n] freshInfo n (b ^ j) b hb := by
  -- on the probability-one event of Section 2.1
  filter_upwards [ae_inUnit n, ae_noGrid n b] with P hP hgrid
  exact funext fun i => Fin.ext
    (fresh_eq_digit hb j (hP i).1.1 fun m r => (hgrid i m r).1).symm

/-- "The `(j+1)`-st digits, which we call the next digits at stage `j`, are independent and
uniform conditional on `𝓕_j`": the conditional expectation, given all heights and the first `j`
digits, of a bounded function of these data and of the next digits is its average over all
values of the next digits. -/
theorem condExp_nextDigits {b : ℕ} (hb : 0 < b) (n j : ℕ)
    (H : (Fin n → ℝ) × (Fin n → Fin j → ℕ) → (Fin n → Fin b) → ℝ)
    (hH : ∀ r, Measurable fun p => H p r) (K : ℝ) (hK : ∀ p r, |H p r| ≤ K) :
    (unifPts n)[fun P => H (digitInfo n b j P) (nextDigits hb n j P) | digitSigma n b j]
      =ᵐ[unifPts n] fun P => finAvg (fun r => H (digitInfo n b j P) r) := by
  -- the statement for the heights and the stage-`j` indices (`condExp_fresh_given_heights`),
  -- for `H` with the first `j` digits read from the indices
  have key := condExp_fresh_given_heights n (b ^ j) b (pow_pos hb j) hb
    (fun p r => H (digitsOfCoarse n b j p) r)
    (fun r => (hH r).comp (measurable_digitsOfCoarse n b j)) K fun p r => hK _ r
  rw [pointSampleLaw_eq_unifPts] at key
  -- almost surely, the first `j` digits are those read from the indices, and the next digits
  -- are the indices of the children
  have hfun : (fun P => H (digitInfo n b j P) (nextDigits hb n j P)) =ᵐ[unifPts n]
      fun P => H (digitsOfCoarse n b j (coarseInfo n (b ^ j) P))
        (freshInfo n (b ^ j) b hb P) := by
    filter_upwards [digitInfo_ae_eq_coarseInfo hb n j, nextDigits_ae_eq_freshInfo hb n j]
      with P hd hr
    rw [hd, hr]
    rfl
  have havg : (fun P => finAvg (fun r => H (digitsOfCoarse n b j (coarseInfo n (b ^ j) P)) r))
      =ᵐ[unifPts n] fun P => finAvg (fun r => H (digitInfo n b j P) r) := by
    filter_upwards [digitInfo_ae_eq_coarseInfo hb n j] with P hd
    rw [hd]
    rfl
  -- conditional expectations given the digits and given the indices agree almost surely
  exact (condExp_digitSigma hb j _).trans ((condExp_congr_ae hfun).trans (key.trans havg))

end

end R56Audit
