import R56Audit.Digits

/-!
# The potential and the fluctuation term are measurable functions of the sample

Auditor's supplement (not part of the audited archive).

The potential `Z_j` of display (1) (`Zpot`) is defined with extrema over the continuum of
heights of each cell. `StageFiltration.lean` and `ConditionalGain.lean` prove that it is almost
surely equal to a measurable function (`Zpot_ae_eq_Zproc`, `Zpot_aestronglyMeasurable`), which
is what the proofs use. This file proves that `Z_j` itself, for every position of the points,
is a Borel measurable function of the sample; hence so is the fluctuation term `T` of display
(10) (`fluct`), and the event `{T ≤ -λ}` of Lemma 2.6 is a measurable set.

The proof is the remark of Section 2.1: "All functions of the height that we consider are
finite linear combinations of the functions `y ↦ 1{V_i ≤ y}`, up to an additive constant. They
take finitely many values, so these extrema exist". The endpoint average `a^{(I)}` of display
(2) is such a combination (`endAvg_eq_stepFn`), with heights and coefficients that are
measurable functions of the sample (`measurable_endAvgCoeff`); and the extrema of such a
function over a vertical interval `B = [s, t)` are extrema over the `n + 1` heights `s` and
`V_i ∈ B` (`maxOn_Ico_stepFn`, `minOn_Ico_stepFn` of `StepOsc.lean`).

* `measurable_osc_Ico_stepFn_comp`: `osc_B (Σ_i c_i 1{V_i ≤ ·})` is a measurable function of a
  parameter on which the heights `V_i` and the coefficients `c_i` depend measurably;
* `measurable_Zpot`: the potential `Z_j` is a measurable function of the sample;
* `measurable_fluct`: the fluctuation term `T` is a measurable function of the sample;
* `measurableSet_fluct_le`: the event `{T ≤ -λ}` of Lemma 2.6 is measurable;
* `measurable_fluctDigits`, `measurableSet_fluctDigits_le`: the same for the fluctuation term
  written with the σ-fields generated by the heights and the digits (`Digits.lean`).
-/

namespace R56Audit

open MeasureTheory Riesz Riesz.PointSets Oscillation

noncomputable section

variable {n : ℕ}

/-! ### Step functions with measurably varying heights and coefficients -/

/-- The value `Σ_i c_i 1{V_i ≤ y}` of a step function is a measurable function of a parameter
on which the heights `V_i`, the coefficients `c_i` and the height `y` depend measurably. -/
lemma measurable_stepFn_comp {α : Type*} [MeasurableSpace α] {V c : α → Fin n → ℝ} {y : α → ℝ}
    (hV : Measurable V) (hc : Measurable c) (hy : Measurable y) :
    Measurable (fun a => stepFn (V a) (c a) (y a)) := by
  unfold stepFn
  refine Finset.measurable_sum _ fun i _ => ?_
  exact Measurable.ite (measurableSet_le ((measurable_pi_apply i).comp hV) hy)
    ((measurable_pi_apply i).comp hc) measurable_const

/-- The oscillation of a step function on a vertical interval `B = [s, t)` is a measurable
function of a parameter on which the heights and the coefficients depend measurably. (For
fixed coefficients this is `measurable_osc_Ico_stepFn`.) -/
theorem measurable_osc_Ico_stepFn_comp {α : Type*} [MeasurableSpace α] {V c : α → Fin n → ℝ}
    (hV : Measurable V) (hc : Measurable c) {s t : ℝ} (hst : s < t) :
    Measurable (fun a => osc (Set.Ico s t) (stepFn (V a) (c a))) := by
  -- the extrema over `B` are the extrema over the candidate heights: `s` and the `V_i ∈ B`
  have h : (fun a => osc (Set.Ico s t) (stepFn (V a) (c a))) = fun a =>
      (⨆ o : Option (Fin n), stepFn (V a) (c a) (candY s t o (V a))) -
        ⨅ o : Option (Fin n), stepFn (V a) (c a) (candY s t o (V a)) := by
    funext a
    unfold osc
    rw [maxOn_Ico_stepFn (V a) (c a) hst, minOn_Ico_stepFn (V a) (c a) hst]
  rw [h]
  -- the value at every candidate height is a measurable function of the parameter
  have hcand : ∀ o : Option (Fin n),
      Measurable (fun a => stepFn (V a) (c a) (candY s t o (V a))) :=
    fun o => measurable_stepFn_comp hV hc ((measurable_candY s t o).comp hV)
  exact (Measurable.iSup hcand).sub (Measurable.iInf hcand)

/-! ### The endpoint average as a step function -/

/-- The coefficient of `1{V_i ≤ y}` in the endpoint average `a^{(I)}(y)` of `I = [xm, xp]`,
for every position of the points: `F_χ(x, y)` counts the point `P_i = (U_i, V_i)`, with its
color, if `0 ≤ U_i ≤ x` and `0 ≤ V_i ≤ y`. (For a point with nonnegative coordinates and
`xm ≤ xp`, this is `χ_i w_i` with the weight `w_i ∈ {1, 1/2, 0}` of display (2).) -/
def endAvgCoeff (χ : Fin n → ℤˣ) (xm xp : ℝ) (P : Fin n → ℝ × ℝ) (i : Fin n) : ℝ :=
  ((if 0 ≤ (P i).1 ∧ (P i).1 ≤ xm ∧ 0 ≤ (P i).2 then sgn χ i else 0) +
    (if 0 ≤ (P i).1 ∧ (P i).1 ≤ xp ∧ 0 ≤ (P i).2 then sgn χ i else 0)) / 2

/-- The endpoint average `a^{(I)}` of display (2) is a step function of the height with jumps
at the heights of the points, for every position of the points. -/
lemma endAvg_eq_stepFn (χ : Fin n → ℤˣ) (P : Fin n → ℝ × ℝ) (xm xp : ℝ) :
    endAvg χ P xm xp = stepFn (fun i => (P i).2) (endAvgCoeff χ xm xp P) := by
  funext y
  unfold endAvg endAvgCoeff
  rw [F_eq_stepFn, F_eq_stepFn, stepFn_div, stepFn_add]

/-- The heights of the points are a measurable function of the sample. -/
lemma measurable_heights :
    Measurable (fun (P : Fin n → ℝ × ℝ) (i : Fin n) => (P i).2) :=
  measurable_pi_iff.mpr fun i => measurable_snd.comp (measurable_pi_apply i)

/-- The coefficients of the endpoint average are a measurable function of the sample. -/
lemma measurable_endAvgCoeff (χ : Fin n → ℤˣ) (xm xp : ℝ) :
    Measurable (endAvgCoeff χ xm xp) := by
  refine measurable_pi_iff.mpr fun i => ?_
  have hU : Measurable (fun P : Fin n → ℝ × ℝ => (P i).1) :=
    measurable_fst.comp (measurable_pi_apply i)
  have hV : Measurable (fun P : Fin n → ℝ × ℝ => (P i).2) :=
    measurable_snd.comp (measurable_pi_apply i)
  -- the event `0 ≤ U_i ≤ x`, `0 ≤ V_i` is measurable, for every `x`
  have hset : ∀ x : ℝ,
      MeasurableSet {P : Fin n → ℝ × ℝ | 0 ≤ (P i).1 ∧ (P i).1 ≤ x ∧ 0 ≤ (P i).2} := fun x =>
    (measurableSet_le measurable_const hU).inter
      ((measurableSet_le hU measurable_const).inter (measurableSet_le measurable_const hV))
  unfold endAvgCoeff
  exact ((Measurable.ite (hset xm) measurable_const measurable_const).add
    (Measurable.ite (hset xp) measurable_const measurable_const)).div_const 2

/-! ### The potential and the fluctuation term -/

/-- The potential `Z_j` of display (1) is a measurable function of the sample. -/
theorem measurable_Zpot {b : ℕ} (hb : 0 < b) (χ : Fin n → ℤˣ) (h j : ℕ) :
    Measurable (Zpot χ b h j) := by
  unfold Zpot
  refine Measurable.div_const ?_ _
  -- one cell `I × B` of stage `j` at a time
  refine Finset.measurable_sum _ fun c _ => Finset.measurable_sum _ fun v _ => ?_
  simp_rw [endAvg_eq_stepFn]
  exact measurable_osc_Ico_stepFn_comp measurable_heights (measurable_endAvgCoeff χ _ _)
    (vcell_lt hb h j v)

/-- The fluctuation term `T` is a measurable function of the sample. -/
theorem measurable_fluct {b : ℕ} (hb : 0 < b) (χ : Fin n → ℤˣ) (h : ℕ) :
    Measurable (fluct χ b h) := by
  unfold fluct
  refine Finset.measurable_sum _ fun j _ => ?_
  -- a conditional expectation given `𝓕_j` is `𝓕_j`-measurable, hence measurable
  have hcond : Measurable ((unifPts n)[Zpot χ b h (j + 1) | stageSigma n b j]) :=
    (StronglyMeasurable.mono stronglyMeasurable_condExp (stageSigma_le n b j)).measurable
  exact (measurable_Zpot hb χ h (j + 1)).sub hcond

/-- The event `{T ≤ -λ}` of Lemma 2.6 is measurable, so its probability is not merely an outer
measure. -/
theorem measurableSet_fluct_le {b : ℕ} (hb : 0 < b) (χ : Fin n → ℤˣ) (h : ℕ) (lam : ℝ) :
    MeasurableSet {P : Fin n → ℝ × ℝ | fluct χ b h P ≤ -lam} :=
  measurableSet_le (measurable_fluct hb χ h) measurable_const

/-- The fluctuation term `T`, with `𝓕_j` generated by the heights and the first `j` digits, is
a measurable function of the sample. -/
theorem measurable_fluctDigits {b : ℕ} (hb : 0 < b) (χ : Fin n → ℤˣ) (h : ℕ) :
    Measurable (fluctDigits χ b h) := by
  unfold fluctDigits
  refine Finset.measurable_sum _ fun j _ => ?_
  have hcond : Measurable ((unifPts n)[Zpot χ b h (j + 1) | digitSigma n b j]) :=
    (StronglyMeasurable.mono stronglyMeasurable_condExp
      (measurable_digitInfo n b j).comap_le).measurable
  exact (measurable_Zpot hb χ h (j + 1)).sub hcond

/-- The event `{T ≤ -λ}` of Lemma 2.6, with `𝓕_j` generated by the heights and the first `j`
digits, is measurable. -/
theorem measurableSet_fluctDigits_le {b : ℕ} (hb : 0 < b) (χ : Fin n → ℤˣ) (h : ℕ) (lam : ℝ) :
    MeasurableSet {P : Fin n → ℝ × ℝ | fluctDigits χ b h P ≤ -lam} :=
  measurableSet_le (measurable_fluctDigits hb χ h) measurable_const

end

end R56Audit
