import R56Audit.ConditionalGain
import R56Audit.CondExpGenerators

/-!
# What one rectangle gives (the remark after Lemma 2.3)

Auditor's supplement (not part of the audited archive).

Section 2.3, last paragraph: "Take `I = [0,1]` and `J = [0,1)`, so that `R` is the unit square
without its top edge. Every oscillation of a child function is at most `2‖F‖∞`, because it is
a difference of two values of `a_k`, and each of them is an average of two values of `F`. So
the left-hand side in Lemma 2.3 is at most `2b E‖F‖∞`. When the heights are fixed and the
horizontal coordinates are independent and uniform, the first digits perform the local
experiment, and the lemma gives `E‖F‖∞ ≥ √(m_R)/(8b)`."

Here the inner region is `R^in = [0,1] × [1/b, 1 - 1/b)` (`unitInnerRegion`), `m_R` is the
number of points in it (`unitInnerCount`), and "When the heights are fixed" is the conditional
expectation given the σ-field generated by all heights (`heightSigma`).

* `one_rectangle`: almost surely, `E[‖F_χ‖∞ | heights] ≥ √(m_R)/(8b)`.

It is Lemma 2.4 for `h = 1` and the transition `0 → 1`, which has the unit square as its only
comparison rectangle (`delta_one_zero`), together with display (9). The σ-field `𝓕_0` is
generated by the heights and by the stage-`0` indices, which are almost surely `0`; so
conditional expectations given `𝓕_0` and given the heights agree (`condExp_heightSigma`).
-/

namespace R56Audit

open MeasureTheory Riesz Riesz.PointSets Oscillation

open scoped Classical

noncomputable section

variable {n : ℕ}

/-- The σ-field generated by all heights. -/
abbrev heightSigma (n : ℕ) : MeasurableSpace (Fin n → ℝ × ℝ) :=
  MeasurableSpace.comap (fun (P : Fin n → ℝ × ℝ) (i : Fin n) => (P i).2) inferInstance

/-- The inner region of the unit square `R = [0,1] × [0,1)`: `R` without its bottom and top
strips of height `1/b`. -/
def unitInnerRegion (b : ℕ) : Set (ℝ × ℝ) :=
  Set.Icc (0 : ℝ) 1 ×ˢ Set.Ico (1 / (b : ℝ)) (1 - 1 / (b : ℝ))

/-- `m_R` for the unit square: the number of points in its inner region. -/
def unitInnerCount (b : ℕ) (P : Fin n → ℝ × ℝ) : ℕ :=
  (Finset.univ.filter (fun i => P i ∈ unitInnerRegion b)).card

/-- For `h = 1`, the comparison rectangle of the transition `0 → 1` is the unit square. -/
lemma innerRegion_one_zero {b : ℕ} (hb : 0 < b) : innerRegion b 1 0 0 0 = unitInnerRegion b := by
  have hbR : (b : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hb.ne'
  -- the top of the inner region: `(b - 1)/b = 1 - 1/b`
  have htop : ((b : ℝ) - 1) / (b : ℝ) = 1 - 1 / (b : ℝ) := by rw [sub_div, div_self hbR]
  unfold innerRegion unitInnerRegion
  -- `I = [0, 1]`, and the heights of the inner region go from `1/b` to `(b - 1)/b`
  simp only [Nat.cast_zero, zero_add, zero_mul, one_mul, pow_zero, pow_one, div_one]
  rw [htop]

/-- A sum over `Fin k` with `k = 1` consists of the term with index `0`. -/
lemma sum_fin_of_eq_one {k : ℕ} (hk : k = 1) (f : ℕ → ℝ) : ∑ c : Fin k, f c = f 0 := by
  rw [Fin.sum_univ_eq_sum_range f k, hk, Finset.sum_range_one]

/-- For `h = 1`, `δ_0 = √(m_R) / (4b)` with `R` the unit square. -/
lemma delta_one_zero {b : ℕ} (hb : 0 < b) (P : Fin n → ℝ × ℝ) :
    delta b 1 0 P = Real.sqrt (unitInnerCount b P) / (4 * (b : ℝ)) := by
  -- `m_R` of the comparison rectangle with indices `(0, 0)`
  have hcount : innerCount b 1 0 P 0 0 = unitInnerCount b P := by
    unfold innerCount unitInnerCount
    rw [innerRegion_one_zero hb]
  -- it is the only comparison rectangle: `b ^ 0 = 1` and `b ^ (1 - 0 - 1) = 1`
  have hsum : ∑ c : Fin (b ^ 0), ∑ v : Fin (b ^ (1 - 0 - 1)), Real.sqrt (innerCount b 1 0 P c v) =
      Real.sqrt (unitInnerCount b P) := by
    rw [sum_fin_of_eq_one (pow_zero b)
        (fun c => ∑ v : Fin (b ^ (1 - 0 - 1)), Real.sqrt (innerCount b 1 0 P c v)),
      sum_fin_of_eq_one (pow_zero b : b ^ (1 - 0 - 1) = 1)
        (fun v => Real.sqrt (innerCount b 1 0 P 0 v)), hcount]
  -- and `M = b ^ (1 - 1) = 1`
  unfold delta
  rw [hsum, Nat.sub_self, pow_zero, mul_one]

/-- For points of `(0,1]²` all stage-`0` indices are `0`: the generator of `𝓕_0` consists of
the heights and of zeros. -/
lemma coarseInfo_pow_zero (b : ℕ) {P : Fin n → ℝ × ℝ} (hP : InUnit P) :
    coarseInfo n (b ^ 0) P = (fun i => (P i).2, fun _ => 0) := by
  refine Prod.ext rfl (funext fun i => ?_)
  -- `0 ≤ gridIndex 1 u` and `gridIndex 1 u + 1 ≤ 1` for `u ∈ (0, 1]`
  obtain ⟨h0, h1⟩ := gridIndex_bounds 1 one_pos (hP i).1
  have h0' : (0 : ℤ) ≤ gridIndex 1 (P i).1 := by exact_mod_cast h0
  have h1' : gridIndex 1 (P i).1 + 1 ≤ 1 := by exact_mod_cast h1
  change gridIndex (b ^ 0) (P i).1 = 0
  rw [pow_zero]
  omega

/-- Conditional expectations given all heights and given `𝓕_0` agree almost surely. -/
theorem condExp_heightSigma (b : ℕ) (f : (Fin n → ℝ × ℝ) → ℝ) :
    (unifPts n)[f | heightSigma n] =ᵐ[unifPts n] (unifPts n)[f | stageSigma n b 0] := by
  have hheights : Measurable (fun (P : Fin n → ℝ × ℝ) (i : Fin n) => (P i).2) :=
    measurable_pi_iff.mpr fun i => measurable_snd.comp (measurable_pi_apply i)
  -- almost surely, the heights determine the generator of `𝓕_0`; the converse always holds
  refine condExp_comap_congr_ae (e := fun V => (V, fun _ => 0)) (e' := Prod.fst) hheights
    (measurable_coarseInfo n (b ^ 0)) (measurable_id.prodMk measurable_const) measurable_fst
    ?_ ?_ f
  · filter_upwards [ae_inUnit n] with P hP
    exact coarseInfo_pow_zero b hP
  · exact Filter.Eventually.of_forall fun P => rfl

/-- `‖F_χ‖∞ ≤ n`, so `‖F_χ‖∞` is integrable. -/
lemma integrable_supNorm (χ : Fin n → ℤˣ) : Integrable (supNorm χ) (unifPts n) := by
  refine Integrable.of_bound (measurable_supNorm χ).aestronglyMeasurable n
    (Filter.Eventually.of_forall fun P => ?_)
  rw [Real.norm_eq_abs, abs_of_nonneg (supNorm_nonneg χ P), supNorm_le_iff]
  exact fun x _ y _ => abs_F_le χ P x y

/-- **What one rectangle gives**: when the heights are fixed, `E‖F_χ‖∞ ≥ √(m_R)/(8b)`, where
`m_R` is the number of points of the unit square with height in `[1/b, 1 - 1/b)`. -/
theorem one_rectangle {b : ℕ} (hb : 2 ≤ b) (χ : Fin n → ℤˣ) :
    ∀ᵐ P ∂unifPts n, Real.sqrt (unitInnerCount b P) / (8 * (b : ℝ)) ≤
      ((unifPts n)[supNorm χ | heightSigma n]) P := by
  have hb0 : 0 < b := by omega
  -- Lemma 2.4 for `h = 1` and the transition `0 → 1`: `δ_0 ≤ E[Z_1 - Z_0 | 𝓕_0]`
  have hgain : ∀ᵐ P ∂unifPts n, delta b 1 0 P ≤
      ((unifPts n)[fun P => Zpot χ b 1 1 P - Zpot χ b 1 0 P | stageSigma n b 0]) P :=
    lemma_2_4 (h := 1) (j := 0) hb one_pos χ
  -- display (9): `Z_1 - Z_0 ≤ 2‖F‖∞`, hence `E[Z_1 - Z_0 | 𝓕_0] ≤ 2 E[‖F‖∞ | 𝓕_0]`
  have hZ : ∀ j ≤ 1, Integrable (Zpot χ b 1 j) (unifPts n) := fun j hj => by
    rw [← pointSampleLaw_eq_unifPts]
    exact integrable_Zpot hb0 hj χ
  have hle : (fun P => Zpot χ b 1 1 P - Zpot χ b 1 0 P) ≤ᵐ[unifPts n] (2 : ℝ) • supNorm χ :=
    Filter.Eventually.of_forall fun P => by
      have h1 : Zpot χ b 1 1 P ≤ 2 * supNorm χ P := Zpot_le_two_supNorm hb0 le_rfl χ P
      have h0 : 0 ≤ Zpot χ b 1 0 P := Zpot_nonneg hb0 χ 1 0 P
      change Zpot χ b 1 1 P - Zpot χ b 1 0 P ≤ 2 * supNorm χ P
      linarith
  have hmono : (unifPts n)[fun P => Zpot χ b 1 1 P - Zpot χ b 1 0 P | stageSigma n b 0]
      ≤ᵐ[unifPts n] (unifPts n)[(2 : ℝ) • supNorm χ | stageSigma n b 0] :=
    condExp_mono ((hZ 1 le_rfl).sub (hZ 0 zero_le_one)) ((integrable_supNorm χ).smul (2 : ℝ)) hle
  have hsmul := condExp_smul (μ := unifPts n) (2 : ℝ) (supNorm χ) (stageSigma n b 0)
  -- conditioning on `𝓕_0` is conditioning on the heights
  filter_upwards [hgain, hmono, hsmul, condExp_heightSigma b (supNorm χ)] with P h1 h2 h3 h4
  -- `√(m_R)/(4b) = δ_0 ≤ E[Z_1 - Z_0 | 𝓕_0] ≤ 2 E[‖F‖∞ | 𝓕_0] = 2 E[‖F‖∞ | heights]`
  rw [delta_one_zero hb0] at h1
  rw [Pi.smul_apply, smul_eq_mul, ← h4] at h3
  -- and `√(m_R)/(8b)` is half of `√(m_R)/(4b)`
  have hhalf : Real.sqrt (unitInnerCount b P) / (8 * (b : ℝ)) =
      Real.sqrt (unitInnerCount b P) / (4 * (b : ℝ)) / 2 := by ring
  linarith

end

end R56Audit
