import R56Audit.Fluctuations
import R56Audit.Crowding
import R56Audit.Digits

/-!
# Proposition 2.7 of the manuscript, by the manuscript's proof

Auditor's supplement (not part of the audited archive).

**Proposition 2.7.** If `M ≤ n`, then

`Pr[∃ χ ∈ {±1}ⁿ : ‖F_χ‖∞ ≤ (h / (64 b^{3/2})) √(n/M)] ≤ h (48/b)^{n/2} + 2ⁿ e^{-hM/(2048 b³)}`.

Here `M = b^(h-1)`. The proof of the manuscript, sentence by sentence:

* "Fix a coloring. Suppose that `G` holds and `‖F‖∞ ≤ hδ_*/8`." The coloring is `χ`. The event
  `G` that all `h` transitions are good is `∀ j < h, GoodTransition b h j P`, and
  `‖F‖∞ ≤ hδ_*/8` is `supNorm χ P ≤ h * deltaStar n b h / 8`.
* `condGain_ge_deltaStar`: "On `G`, every conditional gain is almost surely at least `δ_*`, by
  Lemmas 2.4 and 2.5."
* `Zpot_ge_of_good`: "So (10) and `Z_0 ≥ 0` give `Z_h ≥ hδ_* + T`."
* `Zpot_le_of_small`: "Also `Z_h ≤ hδ_*/4` by (9)."
* `fluct_le_of_good`: "Hence `T ≤ -3hδ_*/4`, and in particular `T ≤ -λ` for `λ = hδ_*/4`."
  The statement is `T ≤ -3hδ_*/4`; the proof of `good_inter_small_le` draws `T ≤ -λ` from it.
* `exponent_eq`: "Since `δ_*² = n/(64b³M)` by (12), the exponent in (13) is then
  `λ²M²/(2hn) = hδ_*²M²/(32n) = hM/(2048b³)`".
* `good_inter_small_le`: "We do not optimize the constants, and apply Lemma 2.6 with this
  `λ`. \[…\] and therefore `Pr[G and ‖F‖∞ ≤ hδ_*/8] ≤ exp(-hM/(2048b³))`."
* `prob_exists_small_le`: "The event `G` does not depend on the coloring. So we bound the
  probability of `G^c` once, by Lemma 2.5, and take a union bound over the colorings only for
  the other event:
  `Pr[∃χ: ‖F_χ‖∞ ≤ hδ_*/8] ≤ Pr(G^c) + Σ_{χ ∈ {±1}ⁿ} Pr[G and ‖F_χ‖∞ ≤ hδ_*/8]`."
* `threshold_eq`, `proposition_2_7`: "Since `hδ_*/8 = h√(n/M)/(64b^{3/2})`, this gives (14)."

**The σ-fields.** The proof uses the σ-fields `digitSigma n b j`, generated by all heights and
by the first `j` base-`b` digits of every horizontal coordinate, and the fluctuation term
`fluctDigits`: these are the manuscript's `𝓕_j` and `T`. They enter through the
manuscript-literal statements of `Digits.lean`: display (10) is `roadmap_digits`, Lemma 2.4 is
`lemma_2_4_digits`, and Lemma 2.6 is `lemma_2_6_digits`. (`Digits.lean` derives these three
statements from `roadmap`, `lemma_2_4` and `lemma_2_6`, which are about the σ-fields
`stageSigma` of the stage-`j` indices and the fluctuation term `fluct`; conditional
expectations given the two σ-fields agree almost surely, by `condExp_digitSigma`. Neither
`stageSigma` nor `fluct` occurs in the statements and proofs of this file.)

Everything here is about the potential `Z_j` of display (1) with heights in the continuum,
the σ-fields `𝓕_j`, and the fluctuation term `T`; the archive's finite-probe potential is
not used. The event of the proposition is stated with `‖F_χ‖∞` and the law `unifPts` of the
points; the archive's point-set interface (`badSet`, `threshold`) is not used, and
`ArchiveInterface.lean` is not imported. The only name of the archive that occurs in this file
is the law `unifPts` (used with the archive's instance that it is a probability measure), as
the `open` lines below show.

The archive's own proofs of display (14) are restated elsewhere: `proposition_2_7_archive` in
`ArchiveRoute.lean` (even `b` or `b ≤ 48`) and `proposition_2_7_probe` in `AllBases.lean` (the
finite-probe route for every `b ≥ 3`).
-/

namespace R56Audit

open MeasureTheory
open Riesz.PointSets (unifPts)

noncomputable section

variable {n : ℕ}

/-- `δ_* ≥ 0`. -/
lemma deltaStar_nonneg (n b h : ℕ) : 0 ≤ deltaStar n b h := by
  unfold deltaStar
  positivity

/-- `δ_* > 0` when there is at least one point. -/
lemma deltaStar_pos {b : ℕ} (hn : 0 < n) (hb : 0 < b) (h : ℕ) : 0 < deltaStar n b h := by
  have hbR : (0 : ℝ) < b := by exact_mod_cast hb
  have hnR : (0 : ℝ) < n := by exact_mod_cast hn
  unfold deltaStar
  have : 0 < Real.sqrt ((n : ℝ) / (b : ℝ) ^ (h - 1)) := Real.sqrt_pos.mpr (by positivity)
  positivity

/-- `δ_*² = n / (64 b³ M)`. -/
lemma deltaStar_sq {b : ℕ} (hb : 0 < b) (n h : ℕ) :
    deltaStar n b h ^ 2 = n / (64 * (b : ℝ) ^ 3 * (b : ℝ) ^ (h - 1)) := by
  have hbR : (0 : ℝ) < b := by exact_mod_cast hb
  have hq : (0 : ℝ) ≤ n / (b : ℝ) ^ (h - 1) := by positivity
  unfold deltaStar
  rw [mul_pow, Real.sq_sqrt hq, rpow_three_halves_eq_mul_sqrt hbR.le, div_pow, mul_pow, mul_pow,
    Real.sq_sqrt hbR.le]
  field_simp
  ring

/-! ### A fixed coloring: `G` and `‖F‖∞ ≤ hδ_*/8` force `T ≤ -3hδ_*/4` -/

/-- "On `G`, every conditional gain is almost surely at least `δ_*`, by Lemmas 2.4 and 2.5."

The conditional gain of the transition `j → j+1` is `E[Z_{j+1} - Z_j | 𝓕_j]`, where `𝓕_j` is
the σ-field `digitSigma n b j` generated by all heights and by the first `j` base-`b` digits
of every horizontal coordinate, and `δ_*` is `deltaStar n b h`, display (12). `G` is the event
that all `h` transitions are good. The statement is for each transition separately: almost
surely, for every `j < h`, if the transition `j → j+1` is good (the event `G_j`), then its
conditional gain is at least `δ_*`. Lemma 2.4 is `lemma_2_4_digits`, and Lemma 2.5(i) is
`lemma_2_5_i`. -/
theorem condGain_ge_deltaStar {b : ℕ} (hb : 2 ≤ b) (h : ℕ) (hn : 0 < n) (χ : Fin n → ℤˣ) :
    ∀ᵐ P ∂unifPts n, ∀ j < h, GoodTransition b h j P → deltaStar n b h ≤
      ((unifPts n)[fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P | digitSigma n b j]) P := by
  have hb0 : 0 < b := by omega
  -- there are finitely many transitions, so it suffices to treat each transition `j → j+1`
  refine (ae_ball_iff (Set.to_countable (Set.Iio h))).mpr fun j hj => ?_
  -- Lemma 2.4: almost surely, its conditional gain is at least `δ_j`
  filter_upwards [lemma_2_4_digits hb hj χ] with P hP hG
  -- Lemma 2.5(i): on `G_j`, `δ_j ≥ δ_*`
  exact (lemma_2_5_i hn hb0 P hG).trans hP

/-- "So (10) and `Z_0 ≥ 0` give `Z_h ≥ hδ_* + T`."

Almost surely, on `G`, the event that all `h` transitions are good. Here `T` is the
fluctuation term `fluctDigits χ b h` of display (10), for the σ-fields `𝓕_j = digitSigma n b j`
generated by all heights and by the first `j` base-`b` digits of every horizontal coordinate.
Display (10) is `roadmap_digits`, and `Z_0 ≥ 0` is `Zpot_nonneg`. -/
theorem Zpot_ge_of_good {b : ℕ} (hb : 2 ≤ b) (h : ℕ) (hn : 0 < n) (χ : Fin n → ℤˣ) :
    ∀ᵐ P ∂unifPts n, (∀ j < h, GoodTransition b h j P) →
      h * deltaStar n b h + fluctDigits χ b h P ≤ Zpot χ b h h P := by
  have hb0 : 0 < b := by omega
  filter_upwards [roadmap_digits hb0 h χ, condGain_ge_deltaStar hb h hn χ] with P hroad hgain hG
  -- on `G`, the `h` conditional gains add up to at least `hδ_*`
  have hsum : (h : ℝ) * deltaStar n b h ≤ ∑ j ∈ Finset.range h,
      ((unifPts n)[fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P | digitSigma n b j]) P :=
    calc (h : ℝ) * deltaStar n b h = ∑ _j ∈ Finset.range h, deltaStar n b h := by
          rw [Finset.sum_const, Finset.card_range, nsmul_eq_mul]
      _ ≤ ∑ j ∈ Finset.range h,
          ((unifPts n)[fun P => Zpot χ b h (j + 1) P - Zpot χ b h j P | digitSigma n b j]) P :=
        Finset.sum_le_sum fun j hj =>
          hgain j (Finset.mem_range.mp hj) (hG j (Finset.mem_range.mp hj))
  -- display (10), and `Z_0 ≥ 0`
  have h0 := Zpot_nonneg hb0 χ h 0 P
  linarith

/-- "Also `Z_h ≤ hδ_*/4` by (9)."

This is under the assumption `‖F‖∞ ≤ hδ_*/8` of the proof; the bound of (9) that is used is
`Z_h ≤ 2‖F‖∞` (`Zpot_le_two_supNorm`). It holds for every position of the points. -/
theorem Zpot_le_of_small {b : ℕ} (hb : 0 < b) (h : ℕ) (χ : Fin n → ℤˣ) (P : Fin n → ℝ × ℝ)
    (hsmall : supNorm χ P ≤ h * deltaStar n b h / 8) :
    Zpot χ b h h P ≤ h * deltaStar n b h / 4 := by
  -- (9): `Z_h ≤ 2‖F‖∞`
  have hZ := Zpot_le_two_supNorm hb (le_refl h) χ P
  linarith

/-- "Hence `T ≤ -3hδ_*/4`, and in particular `T ≤ -λ` for `λ = hδ_*/4`."

Almost surely: if `G` holds, that is, if all `h` transitions are good, and if
`‖F_χ‖∞ ≤ hδ_*/8`, then `T ≤ -3hδ_*/4`. Here `T` is the fluctuation term `fluctDigits χ b h`
of display (10), for the σ-fields `𝓕_j = digitSigma n b j` generated by all heights and by the
first `j` base-`b` digits of every horizontal coordinate. This is the first half of the
sentence; the second half, `T ≤ -λ`, is drawn from it in the proof of `good_inter_small_le`. -/
theorem fluct_le_of_good {b : ℕ} (hb : 2 ≤ b) (h : ℕ) (hn : 0 < n) (χ : Fin n → ℤˣ) :
    ∀ᵐ P ∂unifPts n, (∀ j < h, GoodTransition b h j P) →
      supNorm χ P ≤ h * deltaStar n b h / 8 →
      fluctDigits χ b h P ≤ -(3 * h * deltaStar n b h / 4) := by
  filter_upwards [Zpot_ge_of_good hb h hn χ] with P hge hG hsmall
  -- `Z_h ≥ hδ_* + T` and `Z_h ≤ hδ_*/4`
  have h1 := hge hG
  have h2 := Zpot_le_of_small (by omega : 0 < b) h χ P hsmall
  linarith

/-! ### A fixed coloring: Lemma 2.6 with `λ = hδ_*/4` -/

/-- The exponent display of the proof, for `λ = hδ_*/4` and `M = b^(h-1)`: "Since
`δ_*² = n/(64b³M)` by (12), the exponent in (13) is then
`λ²M²/(2hn) = hδ_*²M²/(32n) = hM/(2048b³)`". The two equalities are the two parts of the
statement; (12) is used in the second one (`deltaStar_sq`). -/
theorem exponent_eq {b : ℕ} (hb : 0 < b) {h : ℕ} (hh : 0 < h) (hn : 0 < n) :
    (h * deltaStar n b h / 4) ^ 2 * ((b : ℝ) ^ (h - 1)) ^ 2 / (2 * h * n) =
        h * deltaStar n b h ^ 2 * ((b : ℝ) ^ (h - 1)) ^ 2 / (32 * n) ∧
      h * deltaStar n b h ^ 2 * ((b : ℝ) ^ (h - 1)) ^ 2 / (32 * n) =
        h * (b : ℝ) ^ (h - 1) / (2048 * (b : ℝ) ^ 3) := by
  have hbR : (0 : ℝ) < b := by exact_mod_cast hb
  have hhR : (0 : ℝ) < h := by exact_mod_cast hh
  have hnR : (0 : ℝ) < n := by exact_mod_cast hn
  constructor
  · -- `λ² = h²δ_*²/16`, and one factor `h` cancels
    field_simp
    ring
  · -- `δ_*² = n/(64b³M)`, by (12)
    rw [deltaStar_sq hb]
    field_simp
    ring

/-- "We do not optimize the constants, and apply Lemma 2.6 with this `λ`. \[…\] and therefore
`Pr[G and ‖F‖∞ ≤ hδ_*/8] ≤ exp(-hM/(2048b³))`."

For a fixed coloring `χ`. `G` is the event that all `h` transitions are good, `λ = hδ_*/4`,
and `M = b^(h-1)`. Lemma 2.6 is `lemma_2_6_digits`, for the fluctuation term
`T = fluctDigits χ b h` of the σ-fields `𝓕_j = digitSigma n b j`. The omitted part is the
exponent display (`exponent_eq`). -/
theorem good_inter_small_le {b h : ℕ} (hb : 2 ≤ b) (hh : 1 ≤ h) (hn : 0 < n) (χ : Fin n → ℤˣ) :
    (unifPts n).real ({P | ∀ j < h, GoodTransition b h j P} ∩
        {P | supNorm χ P ≤ h * deltaStar n b h / 8}) ≤
      Real.exp (-((h : ℝ) * (b : ℝ) ^ (h - 1) / (2048 * (b : ℝ) ^ 3))) := by
  have hb0 : 0 < b := by omega
  have hhR : (0 : ℝ) < h := by exact_mod_cast hh
  have hδ : 0 < deltaStar n b h := deltaStar_pos hn hb0 h
  have hlam : 0 < (h : ℝ) * deltaStar n b h / 4 := by positivity
  -- "apply Lemma 2.6 with this `λ`", that is, with `λ = hδ_*/4`
  have hfl := lemma_2_6_digits hb0 h χ hlam
  -- "the exponent in (13) is then `λ²M²/(2hn) = hδ_*²M²/(32n) = hM/(2048b³)`"
  obtain ⟨hexp1, hexp2⟩ := exponent_eq hb0 hh hn
  rw [hexp1, hexp2] at hfl
  refine le_trans ?_ hfl
  -- almost surely, `G` and `‖F‖∞ ≤ hδ_*/8` imply `T ≤ -λ`
  apply ENNReal.toReal_mono (measure_ne_top _ _)
  apply measure_mono_ae
  filter_upwards [fluct_le_of_good hb h hn χ] with P hP hmem
  -- "Hence `T ≤ -3hδ_*/4`, and in particular `T ≤ -λ` for `λ = hδ_*/4`."
  -- The first inequality is `fluct_le_of_good`; the second one follows because `λ > 0`.
  have hT : fluctDigits χ b h P ≤ -(3 * h * deltaStar n b h / 4) := hP hmem.1 hmem.2
  have hle : -(3 * h * deltaStar n b h / 4) ≤ -(h * deltaStar n b h / 4) := by linarith
  exact hT.trans hle

/-! ### All colorings -/

/-- The number of colorings. -/
lemma card_colorings (n : ℕ) : Fintype.card (Fin n → ℤˣ) = 2 ^ n := by
  rw [Fintype.card_fun, Fintype.card_fin, Fintype.card_units_int]

/-- "Since `hδ_*/8 = h√(n/M)/(64b^{3/2})`, this gives (14)": the threshold `hδ_*/8` of the
proof is the threshold of display (14). Here `M = b^(h-1)`. -/
lemma threshold_eq (n b h : ℕ) :
    h * deltaStar n b h / 8 =
      (h : ℝ) / (64 * (b : ℝ) ^ (3 / 2 : ℝ)) * Real.sqrt (n / (b : ℝ) ^ (h - 1)) := by
  -- by the definition (12) of `δ_*`
  unfold deltaStar
  ring

/-- The union-bound display of the proof: "The event `G` does not depend on the coloring. So
we bound the probability of `G^c` once, by Lemma 2.5, and take a union bound over the
colorings only for the other event:
`Pr[∃χ: ‖F_χ‖∞ ≤ hδ_*/8] ≤ Pr(G^c) + Σ_{χ ∈ {±1}ⁿ} Pr[G and ‖F_χ‖∞ ≤ hδ_*/8]`."

`G` is the event that all `h` transitions are good, so `G^c` is the event that some transition
`j → j+1` with `j < h` is not good. That `G` does not depend on the coloring is visible in the
statement: `GoodTransition b h j P` does not mention `χ`. This statement is the display; the
bound for `Pr(G^c)` by Lemma 2.5 (`lemma_2_5_ii_all`) is inserted in `proposition_2_7`. -/
theorem prob_exists_small_le {b h : ℕ} :
    (unifPts n).real {P | ∃ χ : Fin n → ℤˣ, supNorm χ P ≤ h * deltaStar n b h / 8} ≤
      (unifPts n).real {P | ∃ j, j < h ∧ ¬ GoodTransition b h j P} +
        ∑ χ : Fin n → ℤˣ, (unifPts n).real ({P | ∀ j < h, GoodTransition b h j P} ∩
          {P | supNorm χ P ≤ h * deltaStar n b h / 8}) := by
  -- either `G^c` holds, or `G` holds and some coloring has a small norm
  have hsub : {P : Fin n → ℝ × ℝ | ∃ χ : Fin n → ℤˣ, supNorm χ P ≤ h * deltaStar n b h / 8} ⊆
      {P | ∃ j, j < h ∧ ¬ GoodTransition b h j P} ∪ ⋃ χ : Fin n → ℤˣ,
        ({P | ∀ j < h, GoodTransition b h j P} ∩
          {P | supNorm χ P ≤ h * deltaStar n b h / 8}) := by
    rintro P ⟨χ, hχ⟩
    by_cases hG : ∀ j < h, GoodTransition b h j P
    · exact Or.inr (Set.mem_iUnion.mpr ⟨χ, hG, hχ⟩)
    · push Not at hG
      exact Or.inl hG
  calc (unifPts n).real {P | ∃ χ : Fin n → ℤˣ, supNorm χ P ≤ h * deltaStar n b h / 8}
      ≤ (unifPts n).real ({P | ∃ j, j < h ∧ ¬ GoodTransition b h j P} ∪
          ⋃ χ : Fin n → ℤˣ, ({P | ∀ j < h, GoodTransition b h j P} ∩
            {P | supNorm χ P ≤ h * deltaStar n b h / 8})) := measureReal_mono hsub
    _ ≤ (unifPts n).real {P | ∃ j, j < h ∧ ¬ GoodTransition b h j P} +
          (unifPts n).real (⋃ χ : Fin n → ℤˣ, ({P | ∀ j < h, GoodTransition b h j P} ∩
            {P | supNorm χ P ≤ h * deltaStar n b h / 8})) := measureReal_union_le _ _
    -- the union bound over the colorings, only for the other event
    _ ≤ (unifPts n).real {P | ∃ j, j < h ∧ ¬ GoodTransition b h j P} +
          ∑ χ : Fin n → ℤˣ, (unifPts n).real ({P | ∀ j < h, GoodTransition b h j P} ∩
            {P | supNorm χ P ≤ h * deltaStar n b h / 8}) :=
        add_le_add_right (measureReal_iUnion_fintype_le _) _

/-- **Proposition 2.7 (simultaneous probability bound)**, display (14), with `M = b^{h-1}`:
if `M ≤ n`, then

`Pr[∃ χ ∈ {±1}ⁿ : ‖F_χ‖∞ ≤ (h / (64 b^{3/2})) √(n/M)] ≤ h (48/b)^{n/2} + 2ⁿ e^{-hM/(2048 b³)}`,

for every integer base `b ≥ 3` and every `h ≥ 1`, by the proof of the manuscript: the
identity (10) for the potential of display (1), Lemmas 2.4, 2.5 and 2.6, and a union bound
over the colorings. The last step of the proof: "Since `hδ_*/8 = h√(n/M)/(64b^{3/2})`, this
gives (14)", where "this" is the union-bound display (`prob_exists_small_le`), with the bounds
for its terms (`lemma_2_5_ii_all`, `good_inter_small_le`) and the number `2ⁿ` of colorings
(`card_colorings`). The event is measurable (`measurableSet_exists_supNorm_le`). -/
theorem proposition_2_7 {n b h : ℕ} (hb : 3 ≤ b) (hh : 1 ≤ h) (hMn : b ^ (h - 1) ≤ n) :
    (unifPts n).real {P | ∃ χ : Fin n → ℤˣ,
        supNorm χ P ≤ (h : ℝ) / (64 * (b : ℝ) ^ (3 / 2 : ℝ)) * Real.sqrt (n / (b : ℝ) ^ (h - 1))} ≤
      h * (48 / (b : ℝ)) ^ ((n : ℝ) / 2) +
        2 ^ n * Real.exp (-((h : ℝ) * (b : ℝ) ^ (h - 1) / (2048 * (b : ℝ) ^ 3))) := by
  have hn : 0 < n := lt_of_lt_of_le (pow_pos (by omega) _) hMn
  -- "Since `hδ_*/8 = h√(n/M)/(64b^{3/2})`, this gives (14)."
  rw [← threshold_eq n b h]
  -- the union-bound display
  calc (unifPts n).real {P | ∃ χ : Fin n → ℤˣ, supNorm χ P ≤ h * deltaStar n b h / 8}
      ≤ (unifPts n).real {P | ∃ j, j < h ∧ ¬ GoodTransition b h j P} +
          ∑ χ : Fin n → ℤˣ, (unifPts n).real ({P | ∀ j < h, GoodTransition b h j P} ∩
            {P | supNorm χ P ≤ h * deltaStar n b h / 8}) := prob_exists_small_le
    -- `Pr(G^c) ≤ h (48/b)^{n/2}` by Lemma 2.5, and the bound for each fixed coloring
    _ ≤ h * (48 / (b : ℝ)) ^ ((n : ℝ) / 2) +
          ∑ _χ : Fin n → ℤˣ,
            Real.exp (-((h : ℝ) * (b : ℝ) ^ (h - 1) / (2048 * (b : ℝ) ^ 3))) :=
        add_le_add (lemma_2_5_ii_all hb hMn)
          (Finset.sum_le_sum fun χ _ => good_inter_small_le (by omega) hh hn χ)
    -- there are `2ⁿ` colorings
    _ = h * (48 / (b : ℝ)) ^ ((n : ℝ) / 2) +
          2 ^ n * Real.exp (-((h : ℝ) * (b : ℝ) ^ (h - 1) / (2048 * (b : ℝ) ^ 3))) := by
        rw [Finset.sum_const, Finset.card_univ, card_colorings, nsmul_eq_mul]
        push_cast
        ring

end

end R56Audit
