import R56Audit.ConditionalLaw
import R56Audit.StageGain

/-!
# The σ-fields `𝓕_j` and the potential as a process

Auditor's supplement (not part of the audited archive).

Section 2.4: "Let `𝓕_j` be the σ-field generated by all heights and by the first `j` base-`b`
digits of every horizontal coordinate. The first `j` digits of `U_i` determine the stage-`j`
horizontal interval that contains `U_i`. So `Z_j` is `𝓕_j`-measurable. The `(j+1)`-st digits,
which we call the next digits at stage `j`, are independent and uniform conditional on `𝓕_j`."

| Manuscript | Here |
| --- | --- |
| `𝓕_j` | `stageSigma n b j`, generated by the heights and the stage-`j` indices |
| the filtration `(𝓕_j)` | `stageFiltration n b hb` |
| the next digits at stage `j` | `freshInfo n (b^j) b hb` |
| `Z_j` as a function of the sample | `Zproc ε b h j` (for `j ≤ h`) |
| `E[Z_{j+1} | 𝓕_j]` | `Zmean ε b h j` (`condExp_Zproc_succ`) |

The σ-field `stageSigma n b j` is generated by the heights and by the index of the stage-`j`
horizontal interval `(c b^{-j}, (c+1) b^{-j}]` that contains each `U_i`. The manuscript works
"on the probability-one event that \[…\] no coordinate of a point has the form `k/b^r`"; on
this event the index is the integer whose base-`b` expansion consists of the first `j` digits
of `U_i`. `Digits.lean` proves that conditional expectations given the σ-field generated by
the heights and the digits themselves are almost surely the same.

* `stageFiltration`: the σ-fields increase with `j`;
* `Zproc_stronglyMeasurable`: `Z_j` is `𝓕_j`-measurable;
* `iIndepFun_fresh`, `indepFun_coarse_fresh`: the next digits are independent of each other
  and of `𝓕_j` (Step 2 of the proof of Lemma 2.6);
* `condExp_Zproc_succ`: `E[Z_{j+1} | 𝓕_j]` is the average of `Z_{j+1}` over the next digits;
* `Zmean_ge`: this average is at least `Z_j + δ_j` (Lemma 2.3 in every comparison rectangle);
* `Zpot_ae_eq_Zproc`: almost surely `Zproc` is the potential `Zpot` of the manuscript.
-/

namespace R56Audit

open MeasureTheory ProbabilityTheory Finset Riesz Riesz.PointSets Oscillation

noncomputable section

variable {n : ℕ}

/-! ### The σ-fields -/

/-- `𝓕_j`: the σ-field generated by all heights and by the stage-`j` indices of all horizontal
coordinates. -/
abbrev stageSigma (n b j : ℕ) : MeasurableSpace (Fin n → ℝ × ℝ) :=
  MeasurableSpace.comap (coarseInfo n (b ^ j)) inferInstance

lemma stageSigma_le (n b j : ℕ) :
    stageSigma n b j ≤ (inferInstance : MeasurableSpace (Fin n → ℝ × ℝ)) :=
  (measurable_coarseInfo n (b ^ j)).comap_le

/-- The heights and indices of stage `j + 1` are those of stage `j` together with the next
digits. -/
lemma coarseInfo_succ {b : ℕ} (hb : 0 < b) (j : ℕ) (P : Fin n → ℝ × ℝ) :
    coarseInfo n (b ^ (j + 1)) P =
      ((coarseInfo n (b ^ j) P).1,
        refineIdx (coarseInfo n (b ^ j) P).2 (freshInfo n (b ^ j) b hb P)) :=
  Prod.ext rfl (funext fun i => gridIndex_succ hb j (P i).1)

/-- `𝓕_j ⊆ 𝓕_{j+1}`. -/
lemma stageSigma_succ_le {b : ℕ} (hb : 0 < b) (n j : ℕ) :
    stageSigma n b j ≤ stageSigma n b (j + 1) := by
  refine MeasurableSpace.comap_le_comap_of_eq_comp
    (fun p : (Fin n → ℝ) × (Fin n → ℤ) => (p.1, fun i => p.2 i / (b : ℤ)))
    (measurable_fst.prodMk ((measurable_of_countable
      (fun g : Fin n → ℤ => fun i => g i / (b : ℤ))).comp measurable_snd)) ?_
  funext P
  refine Prod.ext rfl (funext fun i => ?_)
  change gridIndex (b ^ j) (P i).1 = gridIndex (b ^ (j + 1)) (P i).1 / (b : ℤ)
  rw [pow_succ]
  exact (gridIndex_mul_ediv (b ^ j) b hb (P i).1).symm

/-- The filtration `(𝓕_j)_{j ≥ 0}`. -/
def stageFiltration (n b : ℕ) (hb : 0 < b) :
    Filtration ℕ (inferInstance : MeasurableSpace (Fin n → ℝ × ℝ)) where
  seq j := stageSigma n b j
  mono' := monotone_nat_of_le_succ fun j => stageSigma_succ_le hb n j
  le' j := stageSigma_le n b j

/-- The `j`-th σ-field of the filtration is `𝓕_j`. -/
lemma stageFiltration_apply (n b : ℕ) (hb : 0 < b) (j : ℕ) :
    stageFiltration n b hb j = stageSigma n b j := rfl

lemma stageSigma_mono {b : ℕ} (hb : 0 < b) (n : ℕ) {i j : ℕ} (hij : i ≤ j) :
    stageSigma n b i ≤ stageSigma n b j :=
  (stageFiltration n b hb).mono hij

/-! ### The potential as a process -/

/-- The potential at stage `min j h`, as a function of the sample. For `j ≤ h` this is `Z_j`
(`Zproc_eq`, `Zpot_ae_eq_Zproc`). -/
def Zproc (ε : Fin n → ℝ) (b h j : ℕ) (P : Fin n → ℝ × ℝ) : ℝ :=
  Zstep ε b h (min j h) (coarseInfo n (b ^ min j h) P).1 (coarseInfo n (b ^ min j h) P).2

/-- The average of `Z_{j+1}` over all values of the next digits, given the heights and the
stage-`j` indices. -/
def Zmean (ε : Fin n → ℝ) (b h j : ℕ) (P : Fin n → ℝ × ℝ) : ℝ :=
  finAvg (fun r : Fin n → Fin b =>
    Zstep ε b h (j + 1) (coarseInfo n (b ^ j) P).1 (refineIdx (coarseInfo n (b ^ j) P).2 r))

lemma Zproc_eq {b h j : ℕ} (hj : j ≤ h) (ε : Fin n → ℝ) (P : Fin n → ℝ × ℝ) :
    Zproc ε b h j P =
      Zstep ε b h j (coarseInfo n (b ^ j) P).1 (coarseInfo n (b ^ j) P).2 := by
  unfold Zproc
  rw [min_eq_left hj]

/-- `Z_{j+1}` is a function of the heights, the stage-`j` indices and the next digits. -/
lemma Zproc_succ {b h j : ℕ} (hb : 0 < b) (hj : j < h) (ε : Fin n → ℝ) (P : Fin n → ℝ × ℝ) :
    Zproc ε b h (j + 1) P =
      Zstep ε b h (j + 1) (coarseInfo n (b ^ j) P).1
        (refineIdx (coarseInfo n (b ^ j) P).2 (freshInfo n (b ^ j) b hb P)) := by
  rw [Zproc_eq (by omega : j + 1 ≤ h), coarseInfo_succ hb]

/-- The stage-`(j+1)` potential as a measurable function of the heights and stage-`j`
indices, for fixed next digits. -/
lemma measurable_Zstep_refine {b : ℕ} (hb : 0 < b) (ε : Fin n → ℝ) (h j : ℕ)
    (r : Fin n → Fin b) :
    Measurable (fun p : (Fin n → ℝ) × (Fin n → ℤ) => Zstep ε b h j p.1 (refineIdx p.2 r)) := by
  have h2 : Measurable (fun p : (Fin n → ℝ) × (Fin n → ℤ) => (p.1, refineIdx p.2 r)) :=
    measurable_fst.prodMk
      ((measurable_of_countable (fun g : Fin n → ℤ => refineIdx g r)).comp measurable_snd)
  have h3 := (measurable_Zstep_uncurry hb ε h j).comp h2
  exact h3

/-- **`Z_j` is `𝓕_j`-measurable.** -/
theorem Zproc_stronglyMeasurable {b : ℕ} (hb : 0 < b) (ε : Fin n → ℝ) (h j : ℕ) :
    StronglyMeasurable[stageSigma n b j] (Zproc ε b h j) := by
  have h1 : Measurable[stageSigma n b (min j h)] (Zproc ε b h j) :=
    (measurable_Zstep_uncurry hb ε h (min j h)).comp (comap_measurable _)
  exact (h1.mono (stageSigma_mono hb n (min_le_left j h)) le_rfl).stronglyMeasurable

lemma measurable_Zproc {b : ℕ} (hb : 0 < b) (ε : Fin n → ℝ) (h j : ℕ) :
    Measurable (Zproc ε b h j) :=
  ((Zproc_stronglyMeasurable hb ε h j).mono (stageSigma_le n b j)).measurable

/-- The average over the next digits is `𝓕_j`-measurable. -/
theorem Zmean_stronglyMeasurable {b : ℕ} (hb : 0 < b) (ε : Fin n → ℝ) (h j : ℕ) :
    StronglyMeasurable[stageSigma n b j] (Zmean ε b h j) := by
  have h1 : Measurable (fun p : (Fin n → ℝ) × (Fin n → ℤ) =>
      finAvg (fun r : Fin n → Fin b => Zstep ε b h (j + 1) p.1 (refineIdx p.2 r))) :=
    (Finset.measurable_sum _ fun r _ => measurable_Zstep_refine hb ε h (j + 1) r).div_const _
  exact (h1.comp (comap_measurable _)).stronglyMeasurable

lemma measurable_Zmean {b : ℕ} (hb : 0 < b) (ε : Fin n → ℝ) (h j : ℕ) :
    Measurable (Zmean ε b h j) :=
  ((Zmean_stronglyMeasurable hb ε h j).mono (stageSigma_le n b j)).measurable

lemma Zproc_nonneg {b : ℕ} (hb : 0 < b) (ε : Fin n → ℝ) (h j : ℕ) (P : Fin n → ℝ × ℝ) :
    0 ≤ Zproc ε b h j P :=
  Zstep_nonneg hb ε h _ _ _

lemma Zproc_le {b : ℕ} (hb : 0 < b) (ε : Fin n → ℝ) (hε : ∀ i, |ε i| ≤ 1) (h j : ℕ)
    (P : Fin n → ℝ × ℝ) : Zproc ε b h j P ≤ n :=
  Zstep_le hb (min_le_right j h) ε hε _ _

lemma abs_Zproc_le {b : ℕ} (hb : 0 < b) (ε : Fin n → ℝ) (hε : ∀ i, |ε i| ≤ 1) (h j : ℕ)
    (P : Fin n → ℝ × ℝ) : |Zproc ε b h j P| ≤ n :=
  abs_Zstep_le hb (min_le_right j h) ε hε _ _

lemma Zmean_nonneg {b : ℕ} (hb : 0 < b) (ε : Fin n → ℝ) (h j : ℕ) (P : Fin n → ℝ × ℝ) :
    0 ≤ Zmean ε b h j P :=
  finAvg_nonneg fun _ => Zstep_nonneg hb ε h _ _ _

lemma Zmean_le {b h j : ℕ} (hb : 0 < b) (hj : j < h) (ε : Fin n → ℝ) (hε : ∀ i, |ε i| ≤ 1)
    (P : Fin n → ℝ × ℝ) : Zmean ε b h j P ≤ n := by
  have : Nonempty (Fin n → Fin b) := ⟨fun _ => ⟨0, hb⟩⟩
  exact (finAvg_mono fun r => Zstep_le hb (by omega : j + 1 ≤ h) ε hε _ _).trans_eq
    (finAvg_const _)

lemma integrable_Zproc {b : ℕ} (hb : 0 < b) (ε : Fin n → ℝ) (hε : ∀ i, |ε i| ≤ 1) (h j : ℕ) :
    Integrable (Zproc ε b h j) (pointSampleLaw n) :=
  Integrable.of_bound (measurable_Zproc hb ε h j).aestronglyMeasurable n
    (Filter.Eventually.of_forall fun P => by
      rw [Real.norm_eq_abs]
      exact abs_Zproc_le hb ε hε h j P)

/-! ### The next digits -/

/-- **The next digits are independent of each other** (they are functions of different
points). -/
theorem iIndepFun_fresh (n k m : ℕ) (hm : 0 < m) :
    iIndepFun (fun (i : Fin n) (P : Fin n → ℝ × ℝ) => freshGridIndex k m hm (P i).1)
      (pointSampleLaw n) :=
  iIndepFun_pi (X := fun (_ : Fin n) (z : ℝ × ℝ) => freshGridIndex k m hm z.1)
    fun _ => ((measurable_freshGridIndex k m hm).comp measurable_fst).aemeasurable

/-- The joint probability of an event of `𝓕` (given by a measurable set `s` of heights and
indices) and of a set `t` of values of the next digits. -/
lemma measureReal_coarse_inter_fresh (n k m : ℕ) (hk : 0 < k) (hm : 0 < m)
    {s : Set ((Fin n → ℝ) × (Fin n → ℤ))} (hs : MeasurableSet s) (t : Set (Fin n → Fin m)) :
    (pointSampleLaw n).real (coarseInfo n k ⁻¹' s ∩ freshInfo n k m hm ⁻¹' t) =
      (pointSampleLaw n).real (coarseInfo n k ⁻¹' s) *
        finAvg (t.indicator (fun _ => (1 : ℝ))) := by
  classical
  have hc := measurable_coarseInfo n k
  have hf := measurable_freshInfo n k m hm
  have key := integral_fresh_given_heights n k m hk hm
    (fun p r => s.indicator (fun _ => (1 : ℝ)) p * t.indicator (fun _ => (1 : ℝ)) r)
    (fun r => (measurable_const.indicator hs).mul_const _) 1
    (fun p r => by
      rw [abs_mul]
      have h1 : |s.indicator (fun _ => (1 : ℝ)) p| ≤ 1 := by
        by_cases hp : p ∈ s <;> simp [hp]
      have h2 : |t.indicator (fun _ => (1 : ℝ)) r| ≤ 1 := by
        by_cases hr : r ∈ t <;> simp [hr]
      calc |s.indicator (fun _ => (1 : ℝ)) p| * |t.indicator (fun _ => (1 : ℝ)) r| ≤ 1 * 1 :=
            mul_le_mul h1 h2 (abs_nonneg _) zero_le_one
        _ = 1 := one_mul 1)
  have hL : ∫ P, s.indicator (fun _ => (1 : ℝ)) (coarseInfo n k P) *
      t.indicator (fun _ => (1 : ℝ)) (freshInfo n k m hm P) ∂pointSampleLaw n =
      (pointSampleLaw n).real (coarseInfo n k ⁻¹' s ∩ freshInfo n k m hm ⁻¹' t) := by
    rw [← integral_indicator_one ((hc hs).inter (hf (MeasurableSet.of_discrete (s := t))))]
    refine integral_congr_ae (Filter.Eventually.of_forall fun P => ?_)
    by_cases h1 : coarseInfo n k P ∈ s <;> by_cases h2 : freshInfo n k m hm P ∈ t <;>
      simp [Set.indicator, h1, h2]
  have hR : ∫ P, finAvg (fun r => s.indicator (fun _ => (1 : ℝ)) (coarseInfo n k P) *
      t.indicator (fun _ => (1 : ℝ)) r) ∂pointSampleLaw n =
      (pointSampleLaw n).real (coarseInfo n k ⁻¹' s) *
        finAvg (t.indicator (fun _ => (1 : ℝ))) := by
    simp_rw [finAvg_const_mul]
    rw [integral_mul_const, ← integral_indicator_one (hc hs)]
    congr 1
  rw [← hL, key, hR]

/-- **The next digits are independent of `𝓕`**: of the heights and the indices. -/
theorem indepFun_coarse_fresh (n k m : ℕ) (hk : 0 < k) (hm : 0 < m) :
    IndepFun (coarseInfo n k) (freshInfo n k m hm) (pointSampleLaw n) := by
  rw [indepFun_iff_measure_inter_preimage_eq_mul]
  intro s t hs _
  have h1 := measureReal_coarse_inter_fresh n k m hk hm hs t
  have h2 := measureReal_coarse_inter_fresh n k m hk hm MeasurableSet.univ t
  simp only [Set.preimage_univ, Set.univ_inter, probReal_univ, one_mul] at h2
  rw [← h2] at h1
  have h3 : ((pointSampleLaw n) (coarseInfo n k ⁻¹' s ∩ freshInfo n k m hm ⁻¹' t)).toReal =
      ((pointSampleLaw n) (coarseInfo n k ⁻¹' s) *
        (pointSampleLaw n) (freshInfo n k m hm ⁻¹' t)).toReal := by
    rw [ENNReal.toReal_mul]
    exact h1
  exact (ENNReal.toReal_eq_toReal_iff' (measure_ne_top _ _)
    (ENNReal.mul_ne_top (measure_ne_top _ _) (measure_ne_top _ _))).mp h3

/-! ### The conditional expectation of the next potential -/

/-- **`E[Z_{j+1} | 𝓕_j]` is the average of `Z_{j+1}` over the next digits**, almost surely. -/
theorem condExp_Zproc_succ {b h j : ℕ} (hb : 0 < b) (hj : j < h) (ε : Fin n → ℝ)
    (hε : ∀ i, |ε i| ≤ 1) :
    (pointSampleLaw n)[Zproc ε b h (j + 1) | stageSigma n b j] =ᵐ[pointSampleLaw n]
      Zmean ε b h j := by
  have key := condExp_fresh_given_heights n (b ^ j) b (pow_pos hb j) hb
    (fun p r => Zstep ε b h (j + 1) p.1 (refineIdx p.2 r))
    (fun r => measurable_Zstep_refine hb ε h (j + 1) r) n
    (fun p r => abs_Zstep_le hb (by omega : j + 1 ≤ h) ε hε _ _)
  have he : Zproc ε b h (j + 1) = fun P => Zstep ε b h (j + 1) (coarseInfo n (b ^ j) P).1
      (refineIdx (coarseInfo n (b ^ j) P).2 (freshInfo n (b ^ j) b hb P)) :=
    funext fun P => Zproc_succ hb hj ε P
  rw [he]
  exact key

/-- **Lemma 2.3 in every comparison rectangle**: the average of `Z_{j+1}` over the next
digits is at least `Z_j + δ_j`. -/
theorem Zmean_ge {b h j : ℕ} (hb : 2 ≤ b) (hj : j < h) (ε : Fin n → ℝ) (hε : ∀ i, |ε i| = 1)
    (P : Fin n → ℝ × ℝ) :
    Zproc ε b h j P +
        deltaStep b h j (coarseInfo n (b ^ j) P).1 (coarseInfo n (b ^ j) P).2 ≤
      Zmean ε b h j P := by
  rw [Zproc_eq hj.le]
  exact Zstep_gain hb hj ε hε _ _

/-! ### The potential of the manuscript -/

/-- Almost surely, `Zproc` is the potential `Z_j` of the manuscript (display (1)). -/
theorem Zpot_ae_eq_Zproc {b h j : ℕ} (hb : 0 < b) (hj : j ≤ h) (χ : Fin n → ℤˣ) :
    Zpot χ b h j =ᵐ[pointSampleLaw n] Zproc (sgn χ) b h j := by
  filter_upwards [ae_pointSampleLaw_mem_Ioc n] with P hP
  rw [Zpot_eq_Zstep hb χ h j P fun i => ⟨(hP i).1.1.le, (hP i).2.1.le⟩, Zproc_eq hj]
  rfl

end

end R56Audit
