import Riesz.CellAverages
import Mathlib.Probability.Process.Filtration

/-!
# Refinement of the actual uniform grids

The right-closed cell convention is preserved at every level, including at
cell boundaries. Thus refinement holds pointwise, before discarding null
endpoints in the conditional-average identities.
-/

open MeasureTheory

namespace Riesz

/-- The coarse index is integer division of the fine index. -/
theorem gridIndex_mul_ediv (n m : ℕ) (hm : 0 < m) (x : ℝ) :
    gridIndex (n * m) x / (m : ℤ) = gridIndex n x := by
  have hmz : (0 : ℤ) < m := by exact_mod_cast hm
  have hmr : (0 : ℝ) < m := by exact_mod_cast hm
  have hc := Int.ceil_eq_iff.mp (rfl : ⌈(n : ℝ) * x⌉ = ⌈(n : ℝ) * x⌉)
  apply le_antisymm
  · have hb : ⌈((n * m : ℕ) : ℝ) * x⌉ ≤ ⌈(n : ℝ) * x⌉ * (m : ℤ) := by
      apply Int.ceil_le.mpr
      push_cast
      nlinarith [mul_le_mul_of_nonneg_right hc.2 hmr.le]
    have hb' : gridIndex (n * m) x < (gridIndex n x + 1) * (m : ℤ) := by
      simpa only [gridIndex, sub_add_cancel] using
        (show ⌈((n * m : ℕ) : ℝ) * x⌉ - 1 < ⌈(n : ℝ) * x⌉ * (m : ℤ) by omega)
    have := (Int.ediv_lt_iff_lt_mul hmz).mpr hb'
    omega
  · apply (Int.le_ediv_iff_mul_le hmz).mpr
    have hb : (⌈(n : ℝ) * x⌉ - 1) * (m : ℤ) <
        ⌈((n * m : ℕ) : ℝ) * x⌉ := by
      apply Int.lt_ceil.mpr
      push_cast
      nlinarith [mul_lt_mul_of_pos_right hc.1 hmr]
    simp only [gridIndex]
    omega

/-- Every coarse-grid event is a fine-grid event. -/
theorem gridSigma_le_mul (n m : ℕ) (hm : 0 < m) :
    gridSigma n ≤ gridSigma (n * m) := by
  apply MeasurableSpace.comap_le_comap_of_eq_comp (fun k : ℤ ↦ k / (m : ℤ))
    (measurable_of_countable _)
  funext x
  exact (gridIndex_mul_ediv n m hm x).symm

/-- Refinement for arbitrary divisible positive grid sizes. -/
theorem gridSigma_mono_of_dvd {n m : ℕ} (hm : 0 < m) (hnm : n ∣ m) :
    gridSigma n ≤ gridSigma m := by
  obtain ⟨k, rfl⟩ := hnm
  exact gridSigma_le_mul n k (Nat.pos_of_mul_pos_left hm)

/-- Integer division recovers an earlier dyadic cell index. -/
theorem dyadic_gridIndex_ediv {r s : ℕ} (hrs : r ≤ s) (x : ℝ) :
    gridIndex (2 ^ s) x / ((2 ^ (s - r) : ℕ) : ℤ) = gridIndex (2 ^ r) x := by
  have hpow : 2 ^ s = 2 ^ r * 2 ^ (s - r) := by
    rw [← pow_add, Nat.add_sub_of_le hrs]
  rw [hpow]
  exact gridIndex_mul_ediv _ _ (pow_pos (by norm_num) _) x

/-- The sigma-algebras of dyadic grids form an increasing sequence. -/
theorem dyadic_gridSigma_mono : Monotone (fun r : ℕ ↦ gridSigma (2 ^ r)) := by
  intro r s hrs
  exact gridSigma_mono_of_dvd (pow_pos (by norm_num) _) (Nat.pow_dvd_pow 2 hrs)

/-- The filtration generated by right-closed dyadic cells on the real line. -/
noncomputable def dyadicFiltration : Filtration ℕ (inferInstance : MeasurableSpace ℝ) where
  seq r := gridSigma (2 ^ r)
  mono' := dyadic_gridSigma_mono
  le' r := (measurable_gridIndex (2 ^ r)).comap_le

@[simp] theorem dyadicFiltration_apply (r : ℕ) :
    dyadicFiltration r = gridSigma (2 ^ r) := rfl

/-- Every `L`th dyadic level is again a filtration. -/
noncomputable def spacedDyadicFiltration (L : ℕ) :
    Filtration ℕ (inferInstance : MeasurableSpace ℝ) where
  seq j := gridSigma (2 ^ (j * L))
  mono' := fun _ _ hij ↦ dyadic_gridSigma_mono (Nat.mul_le_mul_right L hij)
  le' j := (measurable_gridIndex (2 ^ (j * L))).comap_le

@[simp] theorem spacedDyadicFiltration_apply (L j : ℕ) :
    spacedDyadicFiltration L j = gridSigma (2 ^ (j * L)) := rfl

/-- Every point belongs to the cell selected by its index. -/
theorem mem_gridCell_gridIndex (n : ℕ) (hn : 0 < n) (x : ℝ) :
    x ∈ gridCell n (gridIndex n x) := by
  rw [← gridIndex_fiber n hn]
  simp

/-- Each fine cell lies entirely inside its parent cell. -/
theorem gridCell_subset_parent (n m : ℕ) (hn : 0 < n) (hm : 0 < m) (k : ℤ) :
    gridCell (n * m) k ⊆ gridCell n (k / (m : ℤ)) := by
  intro x hx
  rw [← gridIndex_fiber _ (Nat.mul_pos hn hm)] at hx
  rw [← gridIndex_fiber n hn]
  have hx' : gridIndex (n * m) x = k := hx
  simpa only [Set.mem_preimage, Set.mem_singleton_iff, hx'] using
    (gridIndex_mul_ediv n m hm x).symm

/-- On a fixed fine dyadic cell every earlier cell index is constant. -/
theorem dyadic_gridIndex_eq_on_cell {r s : ℕ} (hrs : r ≤ s) (k : ℤ)
    {x : ℝ} (hx : x ∈ gridCell (2 ^ s) k) :
    gridIndex (2 ^ r) x = k / ((2 ^ (s - r) : ℕ) : ℤ) := by
  rw [← gridIndex_fiber _ (pow_pos (by norm_num) _)] at hx
  have hx' : gridIndex (2 ^ s) x = k := hx
  simpa only [hx'] using (dyadic_gridIndex_ediv hrs x).symm

/-- A dyadic cell is contained in its parent at any earlier level. -/
theorem dyadic_gridCell_subset {r s : ℕ} (hrs : r ≤ s) (k : ℤ) :
    gridCell (2 ^ s) k ⊆ gridCell (2 ^ r) (k / ((2 ^ (s - r) : ℕ) : ℤ)) := by
  intro x hx
  rw [← gridIndex_fiber _ (pow_pos (by norm_num) _)]
  exact dyadic_gridIndex_eq_on_cell hrs k hx

open PointSets

/-- The tower identity for actual uniform-grid averages. -/
theorem condExp_gridMean_of_dvd {n m : ℕ} (hn : 0 < n) (hm : 0 < m)
    (hnm : n ∣ m) {f : ℝ → ℝ} (hf : Integrable f μI) :
    μI[gridMean f m | gridSigma n] =ᵐ[μI] gridMean f n := by
  exact (condExp_congr_ae (condExp_ae_eq_gridMean m hm hf).symm).trans
    ((condExp_condExp_of_le (gridSigma_mono_of_dvd hm hnm)
      (measurable_gridIndex m).comap_le).trans (condExp_ae_eq_gridMean n hn hf))

/-- Fine-minus-coarse grid averages are conditionally centered. -/
theorem condExp_gridMean_sub_of_dvd {n m : ℕ} (hn : 0 < n) (hm : 0 < m)
    (hnm : n ∣ m) {f : ℝ → ℝ} (hf : Integrable f μI) :
    μI[(gridMean f m - gridMean f n) | gridSigma n] =ᵐ[μI] 0 := by
  have hc : μI[gridMean f n | gridSigma n] = gridMean f n :=
    condExp_of_stronglyMeasurable (measurable_gridIndex n).comap_le
      (stronglyMeasurable_gridMean f n) (integrable_gridMean n hn hf)
  refine (condExp_sub (integrable_gridMean m hm hf)
    (integrable_gridMean n hn hf) _).trans ?_
  filter_upwards [condExp_gridMean_of_dvd hn hm hnm hf] with x hx
  simp [Pi.sub_apply, hc, hx]

/-- The last, unaveraged step has the same conditional-centering identity. -/
theorem condExp_sub_gridMean (n : ℕ) (hn : 0 < n) {f : ℝ → ℝ}
    (hf : Integrable f μI) :
    μI[(f - gridMean f n) | gridSigma n] =ᵐ[μI] 0 := by
  have hc : μI[gridMean f n | gridSigma n] = gridMean f n :=
    condExp_of_stronglyMeasurable (measurable_gridIndex n).comap_le
      (stronglyMeasurable_gridMean f n) (integrable_gridMean n hn hf)
  refine (condExp_sub hf (integrable_gridMean n hn hf) _).trans ?_
  filter_upwards [condExp_ae_eq_gridMean n hn hf] with x hx
  simp [Pi.sub_apply, hc, hx]

end Riesz
